Merge Conflict Fix - Add lowering of split like operations
llvm/torch-mlir pull request #1022
Opened 2022-07-07 19:19 UTC by JakopinA

A fix of PR #820, removes the merge conflicts.

2022-07-07 19:22 UTC, JakopinA commented
@gprateek93 Would you mind taking a look at this?

2022-07-07 19:56 UTC, powderluv commented
Please remove "Merge Conflict Fix" in the title

2022-07-07 22:24 UTC, ramiro050 requested changes

2022-07-08 14:29 UTC, JakopinA commented on lib/Dialect/Torch/Transforms/DecomposeComplexOpsEarly.cpp
> +    }
So replace all of that code with ```partial_sum(splitSizes, splitSizes + 1, endIdx);``` ?

2022-07-08 16:59 UTC, ramiro050 commented on lib/Dialect/Torch/Transforms/DecomposeComplexOpsEarly.cpp
> +    }
The first two arguments are the beginning and end of the range of values to partially sum, so it should be `splitSizes.begin(), splitSizes.end()`. The last argument is the iterator to place the result in, so it should be `endIdx.end()`

2022-07-08 17:21 UTC, ramiro050 requested changes
A couple of the changes in the latest commit should've made the e2e tests fail (which you can run by doing `python -m e2e_testing.torchscript.main -f "Split|Chunk" -v`). Please make sure the e2e tests added by your PR are passing locally in your machine before requesting a review. I'm happy to help with questions.

2022-07-08 17:21 UTC, ramiro050 commented on lib/Dialect/Torch/Transforms/DecomposeComplexOpsEarly.cpp
> +        dyn_cast<PrimListConstructOp>(op.self().getDefiningOp());
This is wrong. `op.self()` will never be a `PrimListConstructOp` because it is a tensor.

2022-07-08 17:21 UTC, ramiro050 commented on lib/Dialect/Torch/Transforms/DecomposeComplexOpsEarly.cpp
> -      splitSize = dimSize / chunks;
This is not the right way of addressing my comment regarding templates and dynamic casts. There is still a dynamic cast in line https://github.com/llvm/torch-mlir/blob/705e4f698cc42d7a2e18eba6188785d8d91e1284/lib/Dialect/Torch/Transforms/DecomposeComplexOpsEarly.cpp#L109. There is also no longer valid support for the `AtenChunkOp`. You need to also add a decomposition of `AtenChunkOp` into `AtenSplitTensorOp`.

2022-07-08 17:21 UTC, ramiro050 commented on lib/Dialect/Torch/Transforms/DecomposeComplexOpsEarly.cpp
> +      return rewriter.notifyMatchFailure(op, "int list does not exist");
The error message is not accurate. The right thing to say is something along the lines of `op.split_sizes() must be a constant int list`. You can do `git grep m_TorchConstantIntList` to see example error messages other people have used.

2022-07-08 19:25 UTC, JakopinA commented
I'm unsure why right now, but the tests are not failing because of the changes I made, in fact every single test fails at the moment.

2022-07-08 19:56 UTC, ramiro050 commented
> I'm unsure why right now, but the tests are not failing because of the changes I made, in fact every single test fails at the moment.

What errors are you getting?

2022-07-08 19:58 UTC, JakopinA commented
When running the torchscript file with verbose, I get ```Runtime error: Testing process terminated. Either the compiler crashed or the compiled code crashed at runtime.``` with every single test, not just the split chunk tests.

2022-07-08 20:25 UTC, ramiro050 commented on python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/shape_lib_gen.py
> +    return upstream_shape_helpers.split(self, split_sizes, dim)
These shape functions are outdated. The module `upstream_shape_helpers` should no longer be used in torch-mlir. See: https://github.com/llvm/torch-mlir/pull/1019. The shape functions should be upstreamed into pytorch, and in this file you should use the corresponding `upstream_shape_functions.` function.

I think this is causing the tests to crash. When I try running a simple lowering I get the following error:

```
-:6600:10: error: 'func.call' op '__torch__.torch_mlir.dialects.torch.importer.jit_ir.build_tools.upstream_shape_helpers.maybe_wrap_dim' does not reference a valid function
-:6600:10: note: see current operation: %4 = "func.call"(%arg2, %3, %2) {callee = @__torch__.torch_mlir.dialects.torch.importer.jit_ir.build_tools.upstream_shape_helpers.maybe_wrap_dim} : (!torch.int, !torch.int, !torch.bool) -> !torch.int
```

2022-07-14 03:57 UTC, qedawkins commented
I've been working with this PR and am wondering about the choice to introduce a `DecomposeComplexOpsEarlyPass`. In particular, when trying to compile pytorch-v-diffusion, we end up with the following error:
```
error: failed to legalize operation 'torch.aten._softmax' that was explicitly marked illegal
note: see current operation: %2414 = "torch.aten._softmax"(%2413, %80, %71) : (!torch.vtensor<[2,8,256,256],unk>, !torch.int, !torch.bool) -> !torch.vtensor<[2,8,256,256],unk>
```

Which is thrown because `torch.aten._softmax` fails to decompose due to having an unknown dtype. If we look at the IR for this we see that the loss of shape/type information happens around the `torch.prim.ListUnpack` op at %1410.
```
  %1406 = torch.aten.slice.Tensor %1405, %int1, %int0, %int8, %int1 : !torch.tensor<[2,24,256,64],f32>, !torch.int, !torch.int, !torch.int, !torch.int -> !torch.tensor<[2,8,256,64],f32>
  %1407 = torch.aten.slice.Tensor %1405, %int1, %int8, %int16, %int1 : !torch.tensor<[2,24,256,64],f32>, !torch.int, !torch.int, !torch.int, !torch.int -> !torch.tensor<[2,8,256,64],f32>
  %1408 = torch.aten.slice.Tensor %1405, %int1, %int16, %int24, %int1 : !torch.tensor<[2,24,256,64],f32>, !torch.int, !torch.int, !torch.int, !torch.int -> !torch.tensor<[2,8,256,64],f32>
  %1409 = torch.prim.ListConstruct %1406, %1407, %1408 : (!torch.tensor<[2,8,256,64],f32>, !torch.tensor<[2,8,256,64],f32>, !torch.tensor<[2,8,256,64],f32>) -> !torch.list<tensor>
-------------------------------------------------------------------------
  %1410:3 = torch.prim.ListUnpack %1409 : !torch.list<tensor> -> !torch.tensor, !torch.tensor, !torch.tensor
  %1411 = torch.copy.to_vtensor %1410#0 : !torch.vtensor
  %1412 = torch.aten.mul.Tensor %1411, %67 : !torch.vtensor, !torch.vtensor<[],f64> -> !torch.vtensor
  %1413 = torch.aten.transpose.int %1410#1, %int2, %int3 : !torch.tensor, !torch.int, !torch.int -> !torch.tensor
  %1414 = torch.copy.to_vtensor %1413 : !torch.vtensor
  %1415 = torch.aten.mul.Tensor %1414, %67 : !torch.vtensor, !torch.vtensor<[],f64> -> !torch.vtensor
  %1416 = torch.aten.expand %1412, %1101, %false : !torch.vtensor, !torch.list<int>, !torch.bool -> !torch.vtensor<[?,?,?,?],unk>
  %1417 = torch.aten._reshape_alias %1416, %1103, %1104 : !torch.vtensor<[?,?,?,?],unk>, !torch.list<int>, !torch.list<int> -> !torch.vtensor<[16,256,64],unk>
  %1418 = torch.aten.expand %1415, %1106, %false : !torch.vtensor, !torch.list<int>, !torch.bool -> !torch.vtensor<[?,?,?,?],unk>
  %1419 = torch.aten._reshape_alias %1418, %1108, %1109 : !torch.vtensor<[?,?,?,?],unk>, !torch.list<int>, !torch.list<int> -> !torch.vtensor<[16,64,256],unk>
  %1420 = torch.aten.bmm %1417, %1419 : !torch.vtensor<[16,256,64],unk>, !torch.vtensor<[16,64,256],unk> -> !torch.vtensor<[16,256,256],unk>
  %1421 = torch.aten._unsafe_view %1420, %1112 : !torch.vtensor<[16,256,256],unk>, !torch.list<int> -> !torch.vtensor<[2,8,256,256],unk>
  %1422 = torch.aten._softmax %1421, %int3, %false : !torch.vtensor<[2,8,256,256],unk>, !torch.int, !torch.bool -> !torch.vtensor<[2,8,256,256],unk>

```

Note that %1409 is the last result in the decomposition of an `aten.split_with_sizes` op and %1410 is from the model (it just unpacks the result of the split). I'm not sure if this is a problem caused by the early decomposition introducing a ListConstruct op that we can't handle or if this is a case where we aren't able to handle shape propagation for `torch.prim.ListUnpack`.

My understanding is that the approach of decomposing early was to avoid passing the split-like ops through the shape refinement pass due to returning a list of tensors. Comments from @silvasean or @ramiro050 would be greatly appreciated. If necessary I can open an issue with a MWE; I avoided it in this case because I thought this might be specific to the decomposition strategy used in this PR and thus shouldn't be considered an issue yet.

2022-07-14 16:25 UTC, closed without merging