Add lowering to linalg for softplus and log1p
llvm/torch-mlir pull request #1071
Opened 2022-07-17 19:16 UTC by kkiningh

Adds a straightforward implementation of aten.softplus and log1p. Softplus is used in the [mish activation function](https://github.com/rwightman/pytorch-image-models/blob/326ade299983a1d72b0f4def1299da1bb0f6b6f2/timm/models/layers/activations.py#L29) and log1p is used to implement softplus.

2022-07-17 19:28 UTC, powderluv commented
Thanks for your contributions

2022-07-20 05:44 UTC, vivekkhandelwal1 requested changes
Please rebase it over the latest torch-mlir and resolve the conflicts.

2022-07-20 05:44 UTC, vivekkhandelwal1 commented on python/torch_mlir_e2e_test/test_suite/basic.py
> +    module.forward(tu.rand(3, 3)))
You need to remove this extra brace. `(3, 3)))` ->  `(3, 3))`

2022-07-20 06:33 UTC, vivekkhandelwal1 requested changes
Since you have added a decomposition for the `aten.softplus` op, please add a unit test here: https://github.com/llvm/torch-mlir/blob/main/test/Dialect/Torch/decompose-complex-ops.mlir

2022-07-21 08:05 UTC, vivekkhandelwal1 approved these changes
LGTM

2022-07-25 12:48 UTC, vivekkhandelwal1 commented
@kkiningh Should I merge this PR for you?

2022-07-25 15:26 UTC, kkiningh commented
Please do! I don't have write access.

2022-07-25 15:55 UTC, merged