[MHLO] Add configurable op decomposition rules
llvm/torch-mlir pull request #1172
Opened 2022-08-08 07:50 UTC by Vremold

See RFC #999 
We register some options in `TorchLoweringPipeline` and `DecomposeComplexOpsPass` to make the decomposition rules configurable.

Co-authored-by: Bairen Yi <yibairen.byron@bytedance.com>
Co-authored-by: Jiawei Wu <xremold@gmail.com>
Co-authored-by: Tianyou Guo <tianyou.gty@alibaba-inc.com>
Co-authored-by: Xu Yan <yancey.yx@alibaba-inc.com>
Co-authored-by: Ziheng Jiang <ziheng.jiang@bytedance.com>

2022-08-08 07:57 UTC, fortianyou approved these changes
LGTM

2022-08-08 07:58 UTC, fortianyou commented
Can we add some file check unit tests for the pass?

2022-08-08 08:52 UTC, Vremold commented
> Can we add some file check unit tests for the pass?

Done.

2022-08-08 17:02 UTC, ZihengJiang commented on include/torch-mlir/Dialect/Torch/Transforms/Passes.h
> +      llvm::cl::init(",")};
Can we change the default value to `""` simply?

2022-08-08 17:02 UTC, ZihengJiang approved these changes
Great work!

2022-08-08 22:03 UTC, silvasean requested changes
I have some specific opinions about how we want to do this -- I am on vacation the rest of this week, but after https://github.com/llvm/torch-mlir/pull/1165 lands this was the next thing I was going to work on (and this PR creates a nasty merge conflict). If you can wait for a week or so I would be happy to implement this.

2022-08-08 22:03 UTC, silvasean commented on include/torch-mlir/Dialect/Torch/Transforms/Passes.h
> +  Option<std::string> torchDecompositionSkipOps{
This can be a `list<string>` I think. And it should not have `torch` in the name.

2022-08-08 22:03 UTC, silvasean commented on include/torch-mlir/Dialect/Torch/Transforms/Passes.h
> +  Option<bool> decompose{*this, "decompose-complex-ops",
I would prefer that we have something a bit more principled here. Like one option which is an allowlist and another which is a denylist so users can control it more precisely.

2022-08-09 01:59 UTC, Vremold commented
> I have some specific opinions about how we want to do this -- I am on vacation the rest of this week, but after #1165 lands this was the next thing I was going to work on (and this PR creates a nasty merge conflict). If you can wait for a week or so I would be happy to implement this.

That's okay. I can wait for that.

2022-08-19 02:19 UTC, Vremold commented
There is a better choice in PR #1242 . This PR is useless and closed.

2022-08-19 02:19 UTC, closed without merging