[WIP][TM_TENSOR] Add `aten.scatter_src` op
llvm/torch-mlir pull request #1499
Opened 2022-10-17 16:16 UTC by Shukla-Gaurav

Signed-Off-by: Gaurav Shukla <gaurav@nod-labs.com>

2022-11-10 04:33 UTC, ramiro050 requested changes
Great work on this. This is a very tricky implementation!

2022-11-10 04:33 UTC, ramiro050 commented on lib/Conversion/TorchToTMTensor/TorchToTMTensor.cpp
> +                      b.create<tensor::ExtractOp>(loc, src, indices);
I think this should also be casted to match the input tensor dtype. Can you also add a test where the input tensor is an `int` tensor and the `src` is a `float` tensor to see if the casting is being handled correctly?

2022-11-10 04:33 UTC, ramiro050 commented on lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
> +    Type resultType = selfType.getWithSizesAndDtype(
nit: I think it's clearer to call this `srcType`

2023-04-05 17:40 UTC, Shukla-Gaurav commented
@ramiro050 Thanks for the feedback. It's ready for re-review.

2023-04-06 12:38 UTC, Abhishek-Varma commented
So, a bug has been exposed for negative `dims` case in [convertTorchScatterIndexAndSrcToTMScatterIndexAndSrc](https://github.com/llvm/torch-mlir/blob/e90ea3d7ab66c1b5e858818630261721b3c53d82/lib/Conversion/TorchToTMTensor/TorchToTMTensor.cpp#L85) function.
I've already worked on a patch which aims to provide a fix for the same along with a unit test case -> [Fix aten.scatter for negative dimension](https://gist.github.com/Abhishek-Varma/69ac8b20d24578f9224edc1cd3ef8673)

@Shukla-Gaurav can you incorporate that patch in your patch OR should I add a separate commit for the same?

Since this is needed for [ToMe Support](https://github.com/llvm/torch-mlir/issues/1989) I found that due to negative dimension cases for `aten.scatter` arising, the lowering crashes.

CC: @powderluv @ramiro050

2023-04-06 12:50 UTC, Shukla-Gaurav commented
> So, a bug has been exposed for negative `dims` case in [convertTorchScatterIndexAndSrcToTMScatterIndexAndSrc](https://github.com/llvm/torch-mlir/blob/e90ea3d7ab66c1b5e858818630261721b3c53d82/lib/Conversion/TorchToTMTensor/TorchToTMTensor.cpp#L85) function. I've already worked on a patch which aims to provide a fix for the same along with a unit test case -> [Fix aten.scatter for negative dimension](https://gist.github.com/Abhishek-Varma/69ac8b20d24578f9224edc1cd3ef8673)
> 
> @Shukla-Gaurav can you incorporate that patch in your patch OR should I add a separate commit for the same?
> 
> Since this is needed for [ToMe Support](https://github.com/llvm/torch-mlir/issues/1989) I found that due to negative dimension cases for `aten.scatter` arising, the lowering crashes.
> 
> CC: @powderluv @ramiro050

That seems to be a simple change, so it can be incorporated in the same commit. I will update this patch. Thanks!

2023-04-07 08:39 UTC, Abhishek-Varma commented
Hi @Shukla-Gaurav 

Feel free to use `toPositiveDim` and `isValidDim` instead to enforce the `dim` normalisation. Thanks!

2023-05-24 22:52 UTC, ramiro050 approved these changes
LGTM, just a few small changes

2023-05-24 22:52 UTC, ramiro050 commented on e2e_testing/xfail_sets.py
> +    "ScatterValueFloatModule_basic",
What's the failure error? This list is organized based on the error message. If the error is a new one, can you add it as a comment?

2023-05-24 22:52 UTC, ramiro050 commented on lib/Conversion/TorchToTMTensor/TorchToTMTensor.cpp
> +                                         "have the same number of dimensions.");
nit: clang-format

2023-05-24 22:52 UTC, ramiro050 commented on lib/Conversion/TorchToTMTensor/TorchToTMTensor.cpp
> +      return op.emitError("unimplemented: dim is not constant");
nit: use `notifyMatchFailure` in `matchAndRewrite` patterns instead of `emitError`

2023-05-24 22:52 UTC, ramiro050 commented on lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
> +    addPatternIfTargetOpIsIllegal<DecomposeAtenScatterValueOp>(patterns);
You also need to add this to https://github.com/llvm/torch-mlir/blob/b9b3af8003df35e7094525f9aea3ca605a0da9f9/lib/Dialect/Torch/Transforms/LowerToBackendContract.cpp#L364

2023-05-24 22:52 UTC, ramiro050 commented on lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
> +        llvm::makeArrayRef(indexType.getSizes()), selfType.getDtype());
nit: safer to use `getOptionalSizes` `getOptionalDtype`

2023-05-29 07:05 UTC, merged