[RefineTypes] Fix knowledge dtype for `aten.embedding` op
llvm/torch-mlir pull request #1662
Opened 2022-11-30 11:19 UTC by Abhishek-Varma

-- The dtype of the result of `aten.embedding` should match that of
   the `weight` operand's (operand[0]) instead of hardcoding to f32.
-- This commit aims to provide a fix for the same.

Signed-off-by: Abhishek Varma <abhishek@nod-labs.com>

2022-11-30 12:46 UTC, pashu123 approved these changes
LGTM!

2022-12-01 08:41 UTC, gpetters94 commented
It might be better practice to put the op in [this list](https://github.com/llvm/torch-mlir/blob/d57a16eb1085895d592f0daf2bcc87449bfbc168/lib/Dialect/Torch/Transforms/RefineTypes.cpp#L680).

2022-12-01 14:18 UTC, silvasean requested changes
This change requires an e2e test see https://github.com/llvm/torch-mlir/blob/main/docs/adding_an_e2e_test.md

2022-12-01 14:56 UTC, pashu123 commented
> This change requires an e2e test see https://github.com/llvm/torch-mlir/blob/main/docs/adding_an_e2e_test.md

Let me enable refbackend for float16 types, I guess the conversion support is already there: https://github.com/llvm/llvm-project/blob/main/mlir/python/mlir/runtime/np_to_memref.py

2022-12-01 16:36 UTC, pashu123 commented
@silvasean I have raised the patch for f16 support here: https://github.com/llvm/torch-mlir/pull/1668 This will require https://reviews.llvm.org/D139121 If you could review the patches that would be great.

2022-12-15 15:52 UTC, pashu123 commented
@Abhishek-Varma The float16 support for refbackend is merged, now you can add an e2e test.

2022-12-20 08:53 UTC, Abhishek-Varma commented
Hi @silvasean - I've added one e2e test case. Can you approve now?

2022-12-20 09:17 UTC, silvasean approved these changes

2022-12-20 14:26 UTC, merged