Fix decomposition of aten.linear wrt input rank
llvm/torch-mlir pull request #1740
Opened 2022-12-21 06:09 UTC by xgupta

This fix Failed to legalize operation 'torch.aten.linear' that was explicitly marked illegal #1076. 

As per the comment of @RamirezLucas here - https://github.com/llvm/torch-mlir/issues/1076#issuecomment-1255578687 -

To match the [op documentation](https://pytorch.org/docs/stable/generated/torch.nn.functional.linear.html?highlight=linear), which allows any tensor with rank >= 1, change the expected input tensor rank here - https://github.com/llvm/torch-mlir/blob/4ef6e69ed49f309aa70ea40f12bf7488cd8e3434/lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp#L2078.

2022-12-21 11:03 UTC, RamirezLucas commented
I think you mentioned the wrong person :)

2022-12-21 11:28 UTC, xgupta commented
> I think you mentioned the wrong person :)

Er, sorry for that :)

2022-12-21 18:30 UTC, ramiro050 requested changes
Thanks! Can you also add an e2e test that uses a rank-1 tensor?

2023-01-22 06:40 UTC, xgupta commented
> Thanks! Can you also add an e2e test that uses a rank-1 tensor?

Hi @ramiro050, 

I want to know why the weight rank must be 2 here  - https://github.com/llvm/torch-mlir/blob/1cf09a6a34a4b8b412da85f4fa44757ed0d3622f/lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp#L2499 (one thing I can think of because it is decomposed to aten.matmul). because of this test case is failing with the message - 

```
        torch_mlir.compiler_utils.TorchMlirCompilerError: Lowering TorchScript IR -> Torch Backend IR failed with the following diagnostics:
        error: found an op that was marked as backend illegal
        note: see current operation: %1 = "torch.aten.linear"(%arg0, %arg1, %0) : (!torch.vtensor<[?],f32>, !torch.vtensor<[?,?],f32>, !torch.none) -> !torch.vtensor<[?],f32>
        note: this is likely due to DecomposeComplexOps being unable to decompose this op
```

2023-01-24 21:42 UTC, ramiro050 commented
> > Thanks! Can you also add an e2e test that uses a rank-1 tensor?
> 
> Hi @ramiro050,
> 
> I want to know why the weight rank must be 2 here -
> 
> https://github.com/llvm/torch-mlir/blob/1cf09a6a34a4b8b412da85f4fa44757ed0d3622f/lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp#L2499
> 
> (one thing I can think of because it is decomposed to aten.matmul). because of this test case is failing with the message -
> ```
>         torch_mlir.compiler_utils.TorchMlirCompilerError: Lowering TorchScript IR -> Torch Backend IR failed with the following diagnostics:
>         error: found an op that was marked as backend illegal
>         note: see current operation: %1 = "torch.aten.linear"(%arg0, %arg1, %0) : (!torch.vtensor<[?],f32>, !torch.vtensor<[?,?],f32>, !torch.none) -> !torch.vtensor<[?],f32>
>         note: this is likely due to DecomposeComplexOps being unable to decompose this op
> ```

Must be a similar bug. The documentation says that it can be rank 1 or 2: https://pytorch.org/docs/stable/generated/torch.nn.functional.linear.html?highlight=linear#torch.nn.functional.linear

2024-02-08 12:44 UTC, closed without merging