[MHLO] Support AtenMaskedFillScalar
llvm/torch-mlir pull request #1839
Opened 2023-01-31 23:12 UTC by ZihengJiang

2023-02-01 09:43 UTC, tanyokwok commented on lib/Conversion/TorchToMhlo/Basic.cpp
> +LogicalResult ConvertAtenOp<AtenMaskedFillScalarOp>::matchAndRewrite(
I think we can decompose AtenMaskedFillScalarOp into `AtenWhereScalarSelfOp`, which is more straightforward

2023-02-01 09:45 UTC, tanyokwok commented on lib/Conversion/TorchToMhlo/Basic.cpp
> +LogicalResult ConvertAtenOp<AtenMaskedFillScalarOp>::matchAndRewrite(
And the `AtenWhereScalarSelfOp` can be convert into `mhlo::BroadcastSelectOp`

2023-02-07 20:58 UTC, ZihengJiang commented
The CI is failed due to TOSA failed the `MaskedFillScalarIntValueModule_basic` test, but this test is actually not added into the TOSA_PASS_SET in xfail_sets. Any idea? @ramiro050

2023-02-09 00:40 UTC, ramiro050 commented
The test seems to be passing

```
Unexpected outcome summary:

****** Unexpectedly Passed tests - 1 tests
    XPASS - "MaskedFillScalarIntValueModule_basic"
```

Should just be a matter of adding it to the tosa_pass_set

2023-02-09 00:42 UTC, ramiro050 requested changes

2023-02-09 00:42 UTC, ramiro050 commented on lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
> +class DecomposeAtenMaskedFillScalarOp
I think we can remove the linalg lowering for this op now that we have the decomposition

2023-02-09 00:42 UTC, ramiro050 commented on lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
> +    addPatternIfTargetOpIsIllegal<DecomposeAtenMaskedFillScalarOp>(patterns);
You also need to add the op here: https://github.com/llvm/torch-mlir/blob/eb7bac7ca43ef76581f025fb1c0417308a29582a/lib/Dialect/Torch/Transforms/LowerToBackendContract.cpp#L335

2023-02-10 21:09 UTC, ramiro050 approved these changes
Thanks!

2023-02-10 21:58 UTC, merged