[MHLO] move AtenTanhOp to ConvertAtenUnaryFPOnlyPatten and add sin/co…
llvm/torch-mlir pull request #1847
Opened 2023-02-04 17:40 UTC by qingyunqu

…s/ceil/floor pattern

2023-02-05 02:38 UTC, li-plus commented
LGTM!

2023-02-06 12:08 UTC, li-plus requested changes

2023-02-06 12:08 UTC, li-plus commented on test/Conversion/TorchToMhlo/elementwise.mlir
> +func.func @torch.aten.sin$basic(%arg0: !torch.vtensor<[?,?],f32>) -> !torch.vtensor<[?,?],f32> {
These unit tests are no longer needed. See https://github.com/llvm/torch-mlir/blob/main/docs/architecture.md#dos-and-donts-for-unit-vs-end-to-end-testing.

> DON'T use a unit test if your lowering pattern could be described as a trivial "macro expansion" of one op into another op or set of ops. That is, if you feel like your unit test is just rewriting b.create<...>(...) into CHECK: ... then it is probably not a useful unit test.

2023-02-06 19:13 UTC, ZihengJiang approved these changes

2023-02-06 19:14 UTC, merged