[Torch Dialect] add folder for prim.min.int
llvm/torch-mlir pull request #1864
Opened 2023-02-08 18:00 UTC by qingyunqu

2023-02-09 19:03 UTC, ramiro050 requested changes
Thanks!

2023-02-09 19:03 UTC, ramiro050 commented on test/Dialect/Torch/canonicalize.mlir
> +func.func @torch.prim.min.int$constant() -> !torch.int {
Can you also add e2e tests?

2023-02-10 09:33 UTC, qingyunqu commented on test/Dialect/Torch/canonicalize.mlir
> +func.func @torch.prim.min.int$constant() -> !torch.int {
done

2023-02-10 20:06 UTC, ramiro050 approved these changes

2023-02-10 21:58 UTC, merged