[TORCH] Fix type refinement for aten.cat.
llvm/torch-mlir pull request #1908
Opened 2023-03-01 00:41 UTC by ZihengJiang

Current type refinement implementation for cat is wrong when the operands have diffrent types

2023-03-01 23:14 UTC, ZihengJiang commented on lib/Dialect/Torch/Transforms/RefineTypes.cpp
>          return getLatticeElement(v)->getValue();
@ramiro050  The ValueKnowledge here is just a temporary variable. If we don't store it in the vector, the pointer to it will become invalid?

2023-03-01 23:30 UTC, ramiro050 commented on lib/Dialect/Torch/Transforms/RefineTypes.cpp
>          return getLatticeElement(v)->getValue();
`getLatticeElement` and `getValue` both return references, so the `ValueKnowledge` this function is extracting should stay alive for as long as the `ValueKnowledge` is alive inside the lattice element, which in this function is the entire function.

2023-03-01 23:31 UTC, ramiro050 requested changes

2023-03-01 23:31 UTC, ramiro050 commented on lib/Dialect/Torch/Transforms/RefineTypes.cpp
> -    auto newDtype = meetElementTypes(knowledge.dtype, tensor.dtype);
The CI says that `meetElementTypes` no longer has users. Can you also remove it?

2023-03-08 19:21 UTC, ZihengJiang commented
@ramiro050 PTAL

2023-03-09 21:39 UTC, ramiro050 approved these changes
Great! LGTM

2023-03-09 21:39 UTC, ramiro050 commented on lib/Dialect/Torch/Transforms/RefineTypes.cpp
> +  SmallVector<ValueKnowledge*, 4> tensors = llvm::to_vector<4>(
nit: this vector can have an arbitrary size. Can you remove the `4` from `SmallVector` and `llvm::to_vector`?

https://llvm.org/docs/ProgrammersManual.html#llvm-adt-smallvector-h

2023-03-10 00:17 UTC, merged

2023-03-10 00:17 UTC, ZihengJiang commented
Merged. Thanks @ramiro050