[MLIR][TORCH] Add e2e support for aten.randint
llvm/torch-mlir pull request #2001
Opened 2023-04-04 09:45 UTC by Abhishek-Varma

-- This commit adds e2e support for aten.randint by decomposing it into
   an aten.randint.low by setting low=0.

Signed-off-by: Abhishek Varma <abhishek@nod-labs.com>

2023-04-04 22:26 UTC, ramiro050 requested changes
Thanks! Just a couple small comments

2023-04-04 22:26 UTC, ramiro050 commented on lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
> +    }
nit: this is not needed

2023-04-04 22:26 UTC, ramiro050 commented on lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
> +    addPatternIfTargetOpIsIllegal<DecomposeAtenRandintOp>(patterns);
You also need to add the op here: https://github.com/llvm/torch-mlir/blob/07f5f042c787a51716b1b6d18e3999c04720735e/lib/Dialect/Torch/Transforms/LowerToBackendContract.cpp#L363

2023-04-05 04:23 UTC, Abhishek-Varma commented
> Thanks! Just a couple small comments

Thanks @ramiro050, I've addressed your comments.

2023-04-06 14:34 UTC, ramiro050 approved these changes

2023-04-06 18:43 UTC, merged