[Torch Dialect] Add support for AtenScalarTensorOp
llvm/torch-mlir pull request #2085
Opened 2023-05-02 22:07 UTC by zhekunz2

2023-05-02 22:49 UTC, zhekunz2 commented
Depending on https://github.com/llvm/torch-mlir/pull/2062

2023-05-08 19:22 UTC, ramiro050 requested changes
Can you also add the corresponding shape and dtype functions?

2023-05-08 19:22 UTC, ramiro050 commented on lib/Dialect/Torch/Transforms/RecomposeComplexOps.cpp
> +        op.getDevice(), op.getPinMemory(), cstFalse, cstFalse, cstNone);
nit: add `/*varname=*/var` comments for `cstFalse` and `cstNone`

2023-05-08 19:22 UTC, ramiro050 commented on lib/Dialect/Torch/Transforms/RecomposeComplexOps.cpp
> +    // prim.NumToTensor.Scalar + aten.to.dtype_layout
This is a decomposition, so it should be in `DecomposeComplexOps`. The pattern in this file is for matching on a *series* of ops and (usually) collapsing it to a smaller series of ops that allow further optimizations to take place in torch-mlir.

2023-05-24 22:43 UTC, ramiro050 requested changes

2023-05-24 22:43 UTC, ramiro050 commented on python/torch_mlir_e2e_test/test_suite/basic.py
> +class ScalarTensorFloat32Module(torch.nn.Module):
Can you add a float test without the `dtype` argument to test the default dtype path? PyTorch is a bit weird with how it turns floats to tensors, sometimes they turn into f32, and sometimes into f64

2023-05-24 22:43 UTC, ramiro050 commented on python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/abstract_interp_lib_gen.py
> +def aten〇scalar_tensor〡dtype(s: Union[int, float], dtype: Optional[int] = None, layout: Optional[int] = None, device: Optional[device] = None, pin_memory: Optional[bool] = None) -> int:
Can you add tests to this function? Something like:

https://github.com/llvm/torch-mlir/blob/9c6a58b784df222970b176b28dd27938de7d2859/python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/abstract_interp_lib_gen.py#L1842

to test both possible dtype values for `s`.

2023-05-24 22:43 UTC, ramiro050 commented on lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
> +        /*copy*/ cstFalse, /*memory_format*/ cstNone);
nit: format is `/*var_name=*/var` (missing `=` and remove space)

2023-05-30 21:34 UTC, ramiro050 approved these changes

2023-05-31 06:20 UTC, qingyunqu approved these changes
LGTM

2023-06-01 03:38 UTC, merged