[Torch Op] Add AtenChunkOp support
llvm/torch-mlir pull request #2152
Opened 2023-05-24 00:43 UTC by zhekunz2

Recompose `AtenChunkOp` + `PrimListUnpackOp` to `AtenSliceTensorOp`s.
Recompose rule is equivalent to the following
```
input = chunkOp.getSelf()
chunks = chunkOp.getChunks()
dim = chunkOp.getDim()
totalSize = torch.size(input, dim)
if floordiv(totalSize, chunks) * chunks == totalSize:
    chunkSize = floordiv(totalSize, chunks)
else:
    chunkSize = floordiv(totalSize, chunks) + 1

slices = []
for i in range(primList.numResults()):
    start = chunkSize * i
    if i == primList.numResults() - 1:
        end = totalSize - start
    else:
        end = chunkSize * (i+1)
    slices.append(torch.ops.aten.slice(input, dim, start, end, /*step*/1)

replaceOp(primList, slices)
```

2023-05-24 13:56 UTC, qingyunqu requested changes

2023-05-24 13:56 UTC, qingyunqu commented on lib/Dialect/Torch/Transforms/RecomposeComplexOps.cpp
> +    //    chunkSize = floordiv(totalSize, chunks)
I think it's no need to insert `PrimIfOp`, `chunkSize = floordiv(totalSize + chunks - 1, chunks)` is more simple.

2023-05-25 03:07 UTC, qingyunqu approved these changes

2023-05-25 03:07 UTC, qingyunqu commented
LGTM

2023-05-25 18:45 UTC, ramiro050 approved these changes
Just one small comment, other than that LGTM

2023-05-25 18:45 UTC, ramiro050 commented on lib/Dialect/Torch/Transforms/RecomposeComplexOps.cpp
> +      return failure();
nit: can you use `rewriter.notifyMatchFailure(...)` with an error message? Makes it easier to debug from `-debug` logs

2023-05-26 02:05 UTC, merged