[Torch Dialect] emit aten.tile op and decompose it into aten.repeat
llvm/torch-mlir pull request #2355
Opened 2023-07-29 18:08 UTC by Vremold

2023-08-02 22:15 UTC, ramiro050 requested changes

2023-08-02 22:15 UTC, ramiro050 commented on python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/abstract_interp_lib_gen.py
> +    return _repeat_like_shape_helper(self, dims)
nit: you can call shape functions inside another shape function:

```python
return aten〇repeat〡shape(self, dims)
```

2023-08-02 22:15 UTC, ramiro050 commented on python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/abstract_interp_lib_gen.py
> +def aten〇tile〡shape(self: List[int], dims: List[int]) -> List[int]:
nit: can you add a shape function test for this to make sure the edge case `dims_length < self` works correctly? Here's an example of a test: https://github.com/llvm/torch-mlir/blob/32b1c3dac0dc17ce0b5571c2811c827adf07879e/python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/abstract_interp_lib_gen.py#L345

2023-08-02 22:15 UTC, ramiro050 commented on python/torch_mlir_e2e_test/test_suite/basic.py
> +        return x.tile([3, 4])
Can you also add a test for the `dims_size > input_rank`?

2023-08-03 08:44 UTC, Vremold commented
The comments are addressed in the latest commit.

2023-08-03 22:56 UTC, ramiro050 approved these changes
Thanks!

2023-08-04 01:05 UTC, merged