add e2e support for aten.xlogy.Tensor
llvm/torch-mlir pull request #2486
Opened 2023-09-27 00:13 UTC by saienduri

2023-09-29 22:37 UTC, ramiro050 requested changes
Thanks!

2023-09-29 22:37 UTC, ramiro050 commented on lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
> +// Mish(x) = x * Tanh(Softplus(x))
nit: comment is for the wrong op

2023-09-29 22:37 UTC, ramiro050 commented on lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
> +        IntegerType::get(context, 1));
There is no guarantee that the types will have value semantics at this stage. It is better to create the type from the existing types:

```c++
auto resultType = op.getType().cast<BaseTensorType>();
auto eqType = resultType.getWithSizesAndDtype(
    resultType.getOptionalSizes(), IntegerType::get(context, 1));
```

2023-09-29 22:37 UTC, ramiro050 commented on lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
> +        IntegerType::get(context, 1));
Same comment as above about creating new types

2023-09-29 22:37 UTC, ramiro050 commented on python/torch_mlir_e2e_test/test_suite/elementwise.py
> +    module.forward(tu.rand(3, 5), tu.rand(3, 5))
Can you also add tests that explicitly test the zero and NAN case? (i.e. doing `module.forward(torch.zeros(3, 5), ...)` and `module.forward(... , torch.tensor(float('nan')))`

2023-10-18 19:37 UTC, saienduri commented
NaN case needs some work (not sure if NaN constant is being created properly). will reopen PR when resolved

2023-10-18 19:37 UTC, closed without merging

2026-07-13 08:28 UTC, josephbak commented
I came across this while looking into `aten.xlogy.Tensor` — it still has no lowering path on current `main` (built from source and confirmed it passes through decompose + convert-to-linalg untouched). Looks like the work here was nearly done and just stalled on the NaN-constant handling.

I'd like to try picking it up. I want to dig into that NaN-constant issue first, since it seems to be the crux; if I can sort it out, I'll open a fresh PR with the review feedback here applied (the `getWithSizesAndDtype` change and the zero/NaN test cases).

Is a decomposition for `xlogy` still wanted, or has interest moved on since this closed?

Thanks!