[Torch Dialect] Decompose AtenTriuOp
llvm/torch-mlir pull request #2561
Opened 2023-11-09 01:41 UTC by Mi-Jiazhi

2023-11-09 01:54 UTC, qingyunqu requested changes

2023-11-09 01:54 UTC, qingyunqu commented on projects/pt1/python/torch_mlir_e2e_test/test_suite/elementwise_comparison.py
> +def TriuModule_basic(module, tu: TestUtils):
`TriuModule` => `AtenTriuModule`

2023-11-09 01:54 UTC, qingyunqu commented on lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
> +    // bool *condVal = new bool[rowNum * colNum];
remove this comment

2023-11-09 01:54 UTC, qingyunqu commented on lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
> +    auto colNum = *inputSize.rbegin();
only support tensor with 2 dimensions?  You should check this like constant diagonal.

2023-11-13 04:37 UTC, qingyunqu requested changes

2023-11-13 04:37 UTC, qingyunqu commented on lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
> +            op.getDiagonal().getDefiningOp())) {
=> `if (!matchPattern(op.getDiagonal(), m_TorchConstantInt(&diagonal)) {`

2023-11-13 04:37 UTC, qingyunqu commented on lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
> +    auto inputSize = inputType.getSizes();
I think you should check the `inputType` should have rank >= 2.

2023-11-14 12:56 UTC, qingyunqu approved these changes
LGTM

2023-11-14 12:57 UTC, qingyunqu commented
@ramiro050 Could you please review this PR?

2023-11-15 19:11 UTC, ramiro050 requested changes

2023-11-15 19:11 UTC, ramiro050 commented on lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
> +      return rewriter.notifyMatchFailure(op, "should have static shape and dtype");
I think we can have dynamic support for this op. Here is a potential decomposition:

```python
import torch

def my_triu(x, diag):
    rows = torch.ops.aten.size(x, -2)
    cols = torch.ops.aten.size(x, -1)

    row_indices = torch.ops.aten.arange(rows).unsqueeze(1)
    col_indices = torch.ops.aten.arange(cols).unsqueeze(0)

    cond = torch.ops.aten.ge(
        col_indices, torch.ops.aten.add(row_indices, diag))
    return torch.ops.aten.where(cond, x, 0)

x = torch.rand(5, 7)
assert torch.allclose(my_triu(x, 0), torch.triu(x, 0))
assert torch.allclose(my_triu(x, 1), torch.triu(x, 1))
assert torch.allclose(my_triu(x, 2), torch.triu(x, 2))
assert torch.allclose(my_triu(x, -1), torch.triu(x, -1))

2023-11-28 23:54 UTC, ramiro050 approved these changes
LGTM, just one request

2023-11-28 23:54 UTC, ramiro050 commented on projects/pt1/python/torch_mlir_e2e_test/test_suite/elementwise.py
> +        ([3,4,5,6], torch.float32, True),
Can we also have a test with dynamic shapes?

2023-11-29 02:08 UTC, qingyunqu commented on projects/pt1/python/torch_mlir_e2e_test/test_suite/elementwise.py
>  class AtenTriuWithNegDiagonalModule(torch.nn.Module):
It already has a dynamic shape case here, cc @ramiro050 .

2023-11-29 02:35 UTC, merged