(WIP) implement support (to linalg) for split_dim op
llvm/torch-mlir pull request #2576
Opened 2023-11-14 23:52 UTC by newling

For some reason it looks like the inference is not working correctly. I can't figure out why. 

Running the test 

```
./projects/pt1/tools/e2e_test.sh --filter SplitDim --verbose
```

Results in 
```
****** Failed tests - 1 tests
    FAIL - "SplitDim0Module_basic"
        Compilation error: Traceback (most recent call last):
    
    ... 
        python exception: Failure while executing pass pipeline:
        error: unknown: unsupported by backend contract: tensor with unknown rank
        note: unknown: see current operation: %2 = "torch.tensor_static_info_cast"(%arg0) : (!torch.vtensor<[12,2],f32>) -> !torch.vtensor
        note: unknown: this is likely due to a missing transfer function in abstract_interp_lib_gen.py

        For Torch-MLIR developers, the error can be reproduced with:
        $ torch-mlir-opt -pass-pipeline='builtin.module(torchscript-module-to-torch-backend-pipeline{backend-legal-ops=aten.flatten.using_ints extra-library=})' /tmp/SplitDim0Module.mlir
        Add '-mlir-print-ir-after-all -mlir-disable-threading' to get the IR dump for debugging purpose.
```        

The final IR looks like 

```
<unknown>:0: error: unsupported by backend contract: tensor with unknown rank
<unknown>:0: note: see current operation: %2 = "torch.tensor_static_info_cast"(%arg0) : (!torch.vtensor<[12,2],f32>) -> !torch.vtensor
<unknown>:0: note: this is likely due to a missing transfer function in abstract_interp_lib_gen.py
// -----// IR Dump After LowerToBackendContract Failed (torch-lower-to-backend-contract) //----- //
module attributes {torch.debug_module_name = "SplitDim0Module"} {
  func.func @forward(%arg0: !torch.vtensor<[12,2],f32>) -> !torch.vtensor {
    %int4 = torch.constant.int 4
    %int0 = torch.constant.int 0
    %0 = torch.tensor_static_info_cast %arg0 : !torch.vtensor<[12,2],f32> to !torch.vtensor
    %1 = torch.copy.to_tensor %0 : !torch.tensor
    %2 = torch.prims.split_dim %1, %int0, %int4 : !torch.tensor, !torch.int, !torch.int -> !torch.tensor<[4,3,2],unk>
    %3 = torch.tensor_static_info_cast %2 : !torch.tensor<[4,3,2],unk> to !torch.tensor
    %4 = torch.copy.to_vtensor %3 : !torch.vtensor
    return %4 : !torch.vtensor
  }
}
```

2023-11-15 00:37 UTC, newling commented
Hi @ramiro050 -- following up from yesterday's ops.prims.collapse https://github.com/llvm/torch-mlir/pull/2572 here is the split_dim lowering to linalg. It is basically the same as the collapse lowering, but it doesn't work (described in summary in my first comment). 

If you have any ideas as to why it doesn't work, I would really appreciate any feedback... I've been starting at it for too long now, and thought it might be worth getting an expert to take look.

2023-11-15 19:21 UTC, ramiro050 commented
> I see that one generated class has the ValueSemantic trait the other. Is that relevant?

Yeah, this is likely the source of the error. The op does not have value semantics, but it is just a view-like op (it does not modify the contents of the tensor), so you just need to add it here:

https://github.com/llvm/torch-mlir/blob/e81282ae8f23a34b5a7dbef94bea3dfdf945ebcd/lib/Dialect/Torch/Utils/Utils.cpp#L196

2023-11-15 19:21 UTC, ramiro050 requested changes
A few initial comments

2023-11-15 19:21 UTC, ramiro050 commented on lib/Conversion/TorchToLinalg/Uncategorized.cpp
> +    // The dimension being split ust be statically known.
nit: `ust` -> `must`

2023-11-15 19:21 UTC, ramiro050 commented on lib/Conversion/TorchToLinalg/Uncategorized.cpp
> +  patterns.add<ConvertPrimsSplitDimOp>(typeConverter, context);
nit: remove empty lines to make it consistent

2023-11-15 19:21 UTC, ramiro050 commented on projects/pt1/python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/abstract_interp_lib_gen.py
> +
nit: remove extra whitespace

2023-11-15 19:21 UTC, ramiro050 commented on projects/pt1/python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/abstract_interp_lib_gen.py
> +
nit: remove extra whitespace

2023-11-15 19:21 UTC, ramiro050 commented on projects/pt1/python/torch_mlir_e2e_test/test_suite/elementwise.py
> +
nit: changes to this file not needed

2023-11-15 19:21 UTC, ramiro050 commented on projects/pt1/python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/abstract_interp_lib_gen.py
> +
nit: remove whitespace

2023-11-15 19:21 UTC, ramiro050 commented on lib/Conversion/TorchToLinalg/Uncategorized.cpp
> +
nit: remove whitespace

2023-11-16 05:14 UTC, newling commented
> > I see that one generated class has the ValueSemantic trait the other. Is that relevant?
> 
> Yeah, this is likely the source of the error. The op does not have value semantics, but it is just a view-like op (it does not modify the contents of the tensor), so you just need to add it here:
> 
> https://github.com/llvm/torch-mlir/blob/e81282ae8f23a34b5a7dbef94bea3dfdf945ebcd/lib/Dialect/Torch/Utils/Utils.cpp#L196

That fixed it. Thank you! Will tidy up and address remaining comments soon.

2023-11-20 23:34 UTC, ramiro050 approved these changes
Thanks!

2023-11-21 15:56 UTC, merged