Add aten.min.dim to linalg lowering
llvm/torch-mlir pull request #2600
Opened 2023-11-30 09:19 UTC by frederik-h

2023-11-30 09:24 UTC, frederik-h commented on projects/pt1/python/torch_mlir_e2e_test/test_suite/reduction.py
> +
The test cases have all been adapted from corresponding aten.max test cases.

2023-12-01 23:55 UTC, ramiro050 requested changes
Thanks! I appreciate the thorough updates of comments and variable names.

2023-12-01 23:55 UTC, ramiro050 commented on projects/pt1/e2e_testing/xfail_sets.py
> +    "ReduceMinAlongDimUnsignedInt_basic",
What's the error you're getting? I only see the `AtenMaxDim` test xfailed for the Torchdynamo backend, not the linalg backend, so I would expect the `AtenMinDim` test to work for the linalg backend.

2023-12-04 08:31 UTC, frederik-h commented on lib/Conversion/TorchToLinalg/Reduction.cpp
> +template <> constexpr bool isMaxDimOp<AtenMinDimOp>() { return false; }
Right! I have changed it now.

2023-12-04 23:21 UTC, ramiro050 approved these changes
Thanks!

2023-12-04 23:21 UTC, ramiro050 commented on projects/pt1/e2e_testing/xfail_sets.py
> +    "ReduceMinAlongDimUnsignedInt_basic",
Ah, good catch. Yeah, having the XFAIL is fine then.

2023-12-05 07:36 UTC, frederik-h commented
> Thanks!

@ramiro050 Thanks for your helpful review!

2023-12-05 15:00 UTC, frederik-h commented
> > Thanks!
> 
> @ramiro050 Thanks for your helpful review!

@ramiro050 @vivekkhandelwal1 Just for my understanding: Is one approving review enough and someone just needs to merge this (I cannot) or are we waiting for another review?

2023-12-05 15:15 UTC, stellaraccident commented
Ramiro approving such a patch is certainly enough. Having a quick look and will merge.

2023-12-05 15:16 UTC, merged