[ONNX][MLIR] Add support for onnx.gather op
llvm/torch-mlir pull request #2726
Opened 2024-01-04 17:43 UTC by Shukla-Gaurav

This commit adds support for gather op in the onnx pipeline.

2024-01-15 14:04 UTC, Shukla-Gaurav commented
@stellaraccident @rsuderman @vivekkhandelwal1 @renxida Can you please review this PR?

2024-01-16 07:37 UTC, vivekkhandelwal1 reviewed
Hi @Shukla-Gaurav, it would be better if you can add a small comment explaining your approach since this is not a straight-forward lowering, and it would be hard for us to understand this by ourselves and then review.

2024-01-16 17:33 UTC, Shukla-Gaurav commented
@vivekkhandelwal1 Sure, will add a comment explaining the algorithm in the lowering code itself. Meanwhile you can review it by checking the algorithm here https://github.com/nod-ai/SHARK-Turbine/issues/242

2024-01-16 19:13 UTC, rsuderman requested changes
+1 on having the high level description. I can see several constructions being performed but not interpret how this generates a `onnx.gather` behavior.

2024-01-16 19:13 UTC, rsuderman commented on lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp
> +                Torch::ListType::get(Torch::IntType::get(indices.getContext())),
You can also do
```
rewriter.getType<Torch::ListType>(rewriter.getType<Torch::IntType>());
```

2024-01-18 17:01 UTC, Shukla-Gaurav commented
@rsuderman @vivekkhandelwal1  
Added high level description of the conversion. Could you please review again? Thanks!

2024-01-18 21:32 UTC, rsuderman approved these changes
Just some minor nits but LGTM otherwise

2024-01-18 21:32 UTC, rsuderman commented on lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp
> +          if (dim == -1) {
We should use `Torch::kUnknownSize` instead

2024-01-19 16:28 UTC, merged

2024-06-12 03:13 UTC, AmosLewis commented
Gather failed again in Shark-TestSuites onnx model opt-125M-awq:
`python ./run.py --torchmlirbuild ../../torch-mlir/build --tolerance 0.001 0.001 --cachedir ./huggingface_cache --ireebuild ../../iree-build  -f onnx -g models --mode onnx --report  --torchtolinalg --tests onnx/models/opt-125M-awq
`
```
opt-125M-awq.default.torch-onnx.mlir:1123:13: error: 'tensor.expand_shape' op expected number of static shape dims to be equal to the output rank (3) but found 0 inputs instead
    %1119 = torch.operator "onnx.Gather"(%0, %1113) : (!torch.vtensor<[50272,768],f32>, !torch.vtensor<[?,?],si64>) -> !torch.vtensor<[?,?,768],f32> 
            ^
opt-125M-awq.default.torch-onnx.mlir:1123:13: note: see current operation: %1049 = "tensor.expand_shape"(%1046) <{reassociation = [[0, 1], [2]], static_output_shape = array<i64>}> : (tensor<?x768xf32>) -> tensor<?x?x768xf32>

```