[Torch Dialect] support aten.isneginf, aten.isposinf, aten.nan_to_num
llvm/torch-mlir pull request #2743
Opened 2024-01-11 07:47 UTC by linuxlonelyeagle

2024-01-12 18:00 UTC, qingyunqu requested changes

2024-01-12 18:00 UTC, qingyunqu commented on lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
> +    Value lan = op.getNan();
nit: `Value lan` => `Value nan`

2024-01-12 18:02 UTC, qingyunqu commented on projects/pt1/python/torch_mlir_e2e_test/test_suite/elementwise.py
> +            [1, float('-inf'), float('-inf'), float('nan'), 3],
change some `-inf` to `inf` to make this test more robust? Same as test of `aten.isposinf`.

2024-01-13 03:05 UTC, qingyunqu approved these changes
LGTM

2024-01-13 03:06 UTC, qingyunqu commented
@ramiro050 Could you please review this?

2024-01-16 06:11 UTC, Vremold approved these changes
LGTM. Thanks for the effort.

2024-01-16 06:29 UTC, merged