[onnx] Lowering `onnx.dequantize_linear` to `torch`
llvm/torch-mlir pull request #2759
Opened 2024-01-15 22:26 UTC by rsuderman

We can make the per-tensor version of the operation to the dequantize operation via marking with the make quantized tensor component. This introductions the `qint*` and `quint*` tensor type that can be lowered to teh appropriate dequantization behavior during the torch-to-linalg conversion.

2024-01-16 07:52 UTC, vivekkhandelwal1 commented
Hi @rsuderman, I had taken this op for the lowering. I'm not sure if you went through this https://github.com/nod-ai/SHARK-Turbine/issues/334 or not.

2024-01-16 16:27 UTC, vivekkhandelwal1 requested changes

2024-01-16 16:29 UTC, vivekkhandelwal1 commented on lib/Conversion/TorchOnnxToTorch/DefaultDomainAtoF.cpp
> +                  binder.getLoc(), qTensorTy, operand, scale, zeropoint);
I think this won't handle per-axis quantization tensor op.

2024-01-16 20:12 UTC, rsuderman commented on lib/Conversion/TorchOnnxToTorch/DefaultDomainAtoF.cpp
> +        Value zeropoint = operands[2];
Changed to pull the value conditionally.

2024-01-16 20:14 UTC, rsuderman commented on lib/Conversion/TorchOnnxToTorch/DefaultDomainAtoF.cpp
> +        if (scaleTy.getSizes().size() == 0) {
It is not yet supported. In a follow up we can do a similar trick with `AtenMakePerChannelQuantzedOp` but per-tensor should be good enough for now.

2024-01-16 20:14 UTC, rsuderman commented on lib/Conversion/TorchOnnxToTorch/DefaultDomainAtoF.cpp
> +              binder.getLoc(), rewriter.getType<Torch::IntType>(), zeropoint);
Correct, however we verified above that the tensor is already rank-0.

2024-01-17 16:08 UTC, vivekkhandelwal1 commented on lib/Conversion/TorchOnnxToTorch/DefaultDomainAtoF.cpp
> +                  binder.getLoc(), qTensorTy, operand, scale, zeropoint);
Okay

2024-01-17 16:10 UTC, vivekkhandelwal1 approved these changes
LGTM

2024-01-17 19:52 UTC, rsuderman commented
> Hi @rsuderman, I had taken this op for the lowering. I'm not sure if you went through this [nod-ai/SHARK-Turbine#334](https://github.com/nod-ai/SHARK-Turbine/issues/334) or not.

Generally the quantization work needs to be separated out from the general op-by-op lowering work. Because `torch` depends on sidechanneling quantization information it is likely we will need passes to propagate / setup the sidechannelled zero-point / scale information.

2024-01-19 00:47 UTC, merged