fix only cumsum - leaving the view canonicalizer for a separate patch
llvm/torch-mlir pull request #2849
Opened 2024-02-01 22:54 UTC by renxida

Thanks for the idea @newling

2024-02-01 23:23 UTC, newling commented
Tests in Dialect/Torch/canonicalize.mlir if possible please

I think it's fine but I'm not experienced enough with torch-mlir to sign off on this -- I'm not sure if DenseElementsAttr are supported (I can see folders returning IntegerAttr, none return DenseElementsAttr). Please get another review.

2024-02-02 06:08 UTC, rsuderman requested changes

2024-02-02 06:08 UTC, rsuderman commented on include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td
> +  let hasFolder = 1;
You may need to rerun the generator as this does not have an implementation and is no longer specified in the script.

2024-02-02 06:08 UTC, rsuderman commented on lib/Dialect/Torch/IR/TorchOps.cpp
> +  } else if (elementType.isa<FloatType>()) {
You might as well drop the `else` of each of these statements as each returns a value.

Repeat for the other sections below.

2024-02-02 06:08 UTC, rsuderman commented on test/Dialect/Torch/canonicalize.mlir
> +// ensure a constant int is created and returned
Don't both including this comment. The check statements are fairly straightforward

2024-02-02 06:08 UTC, rsuderman commented on test/Dialect/Torch/canonicalize.mlir
> +// test that we can fold the constant when we chain
Same with this comment. The IR is pretty sufficient.

2024-02-02 06:08 UTC, rsuderman commented on test/Dialect/Torch/canonicalize.mlir
> +// test that we can fold the constant when we chain
Ditto for removing.

2024-02-02 18:15 UTC, renxida reviewed
addressed!

2024-02-02 18:44 UTC, rsuderman approved these changes

2024-02-02 18:46 UTC, merged