e2e support aten.linalg_norm to aten.linalg_vector_norm
llvm/torch-mlir pull request #2953
Opened 2024-02-27 05:59 UTC by zezhang

Add e2d support for `aten.linalg_norm` by decompose it to  `aten.linalg_vector_norm`. 

Lowering to `aten.linalg_matrix_norm` is still unsupported.

To Test: 

`python -m e2e_testing.main -v`

2024-02-27 06:55 UTC, navahgar reviewed
LGTM. I will let @ramiro050 approve this to ensure this decomposition is okay.

2024-02-29 00:42 UTC, ramiro050 requested changes
Looks mostly good. Just a few small comments

2024-02-29 00:42 UTC, ramiro050 commented on lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
> +          dyn_cast<Torch::PrimListConstructOp>(op.getDim().getDefiningOp());
nit: we have a helper for getting a list construct:

https://github.com/llvm/torch-mlir/blob/e85a2a87c5662c26e047a2d93d3ff6216cabdcec/lib/Dialect/Torch/Utils/Utils.cpp#L38

2024-02-29 00:42 UTC, ramiro050 commented on lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
> +    if (dyn_cast_or_null<ConstantNoneOp>(ord.getDefiningOp())) {
nit: to avoid relying on `getDefiningOp`, you can do `ord.getType().isa<Torch::NoneType>()`

2024-02-29 00:42 UTC, ramiro050 commented on test/Dialect/Torch/decompose-complex-ops.mlir
No need to add this. e2e tests are sufficient. See: https://github.com/llvm/torch-mlir/blob/main/docs/architecture.md#dos-and-donts-for-unit-vs-end-to-end-testing

2024-02-29 00:42 UTC, ramiro050 commented on lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
> +    addPatternIfTargetOpIsIllegal<DecomposeAtenLinalgNormOp>(patterns);
You also need to add it here: https://github.com/llvm/torch-mlir/blob/e85a2a87c5662c26e047a2d93d3ff6216cabdcec/lib/Dialect/Torch/Transforms/LowerToBackendContract.cpp#L367

2024-03-05 17:54 UTC, zezhang commented
@ramiro050 If you could take another look before merging.

2024-03-06 00:24 UTC, ramiro050 approved these changes
LGTM! Thanks

2024-03-06 00:31 UTC, merged