[MLIR][ONNX] Add OnnxToTorch support for MaxRoiPool Op
llvm/torch-mlir pull request #3395
Opened 2024-05-29 01:23 UTC by suryajasper

This PR adds OnnxToTorch support for MaxRoiPool op

2024-06-03 16:11 UTC, vivekkhandelwal1 commented
Hi @suryajasper, can you please format the code as per the CI failures?

2024-06-03 17:02 UTC, suryajasper commented
Hi @vivekkhandelwal1, formatting issues are resolved

2024-06-10 08:09 UTC, vivekkhandelwal1 requested changes
Thanks for adding the patch @suryajasper. You have written very clean code. I hope you've verified the e2e correctness of this code through SHARK-Testsuite. Please address the minor comments.

2024-06-10 23:59 UTC, suryajasper commented on lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp
> +            roisFloatTy.getSizes(), floatTy);
I was able to remove a few redundancies here, but the remaining type variables in the code are necessary as the design of the ONNX operation requires a lot of type and shape manipulation of the input tensors.

2024-06-10 23:59 UTC, suryajasper commented on lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp
> +          return failure();
Fixed!

2024-06-10 23:59 UTC, suryajasper commented on lib/Conversion/TorchOnnxToTorch/DefaultDomainGtoP.cpp
> +        int64_t numRois = roisShape[0];
Fixed!

2024-06-12 15:29 UTC, vivekkhandelwal1 approved these changes

2024-06-13 05:16 UTC, merged