[LINALG] Implement lowering of torch.aten.rot90
llvm/torch-mlir pull request #3551
Opened 2024-07-19 10:06 UTC by BaneTrifa

2024-08-14 11:52 UTC, vivekkhandelwal1 requested changes

2024-08-14 11:52 UTC, vivekkhandelwal1 commented on lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
> +        loc, rewriter.getI64IntegerAttr(dim1));
Is this really required? We're extracting the integer value out of the `TorchConstantInt` and then again creating a `TorchConstantInt` with that integer value.

2024-08-14 11:52 UTC, vivekkhandelwal1 commented on lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
> +#include "mlir/Dialect/Linalg/IR/Linalg.h"
I think this is not required.

2024-08-14 11:52 UTC, vivekkhandelwal1 commented on projects/pt1/python/torch_mlir_e2e_test/test_suite/reshape_like.py
> +    module.forward(tu.rand(6, 2, 4))
`Dyms` -> `Dims`

2024-08-22 10:45 UTC, vivekkhandelwal1 approved these changes

2024-08-22 13:11 UTC, BaneTrifa commented
Can you please merge this PR? @vivekkhandelwal1

2024-09-06 05:06 UTC, merged