Implement lowering of torch.aten.hstack
llvm/torch-mlir pull request #3563
Opened 2024-07-25 11:27 UTC by BaneTrifa

2024-08-14 11:34 UTC, vivekkhandelwal1 requested changes

2024-08-14 11:34 UTC, vivekkhandelwal1 commented on lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
> +    }
Before doing this, shouldn't we check whether the tensors are already of rank >= 1 or not? Otherwise, this would result in a lot of unusable code.

2024-08-14 11:34 UTC, vivekkhandelwal1 commented on lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
> +        rewriter.create<ConstantIntOp>(loc, rewriter.getI64IntegerAttr(1));
Since, either of these constants would be used, I would suggest to combine them with the code where the Cat op is created inside if-else.

2024-08-22 10:44 UTC, vivekkhandelwal1 approved these changes

2024-08-22 13:10 UTC, BaneTrifa commented
Can you please merge this PR? @vivekkhandelwal1

2024-09-11 11:11 UTC, merged