[TorchToLinalg] Implement lowering of torch.aten.rrelu_with_noise and torch.aten.rrelu_with_noise_backward ops (fix)
llvm/torch-mlir pull request #3748
Opened 2024-09-30 12:10 UTC by bosko-syrmia

As title. @vivekkhandelwal1 This PR finalizes and resolves issues from #3645. Updated `xfail_set` and cherry-picked previous implementation.

2024-10-23 12:53 UTC, vivekkhandelwal1 requested changes
Just a small change, and the rest looks good.

2024-10-25 11:55 UTC, vivekkhandelwal1 approved these changes
LGTM

2024-10-25 11:55 UTC, vivekkhandelwal1 commented on lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
> +    }
Sorry, I missed that difference.

2024-10-25 16:01 UTC, merged

2024-10-29 21:14 UTC, zjgarvey commented
Hey @vivekkhandelwal1 this seems to be the commit that caused the CI to break on nightly.

2024-10-30 11:21 UTC, bosko-syrmia commented
It seems that some tests started failing on later nightly builds, after I committed last changes. So I made this PR #3835 that addresses those issues.