Add `aten.stft.center` and decomposition
llvm/torch-mlir pull request #3880
Opened 2024-11-18 17:01 UTC by giacs-epic

DRAFT because it depends on https://github.com/llvm/torch-mlir/pull/3857

The choice to work with `aten.stft.center` instead of `aten.stft` is because the latter doesn't match the signature that gets exposed (see https://pytorch.org/docs/stable/generated/torch.stft.html).

2025-01-09 09:23 UTC, giacs-epic commented
CI errors (undefined symbols referenced by `LazyNativeFunctions.cpp`) are unrelated to the PR content.

2025-02-17 23:19 UTC, zjgarvey commented
Might need to add tosa xfails if you haven't done so already. IIRC Tosa got added to the CI in your last sync.

2025-02-18 19:42 UTC, zjgarvey requested changes
A general comment before reviewing further:

Is it absolutely necessary to use a loop? The only times I would ever consider using a loop is if there is a necessary loop-carried dependency, but I don't think that is the case here. 

Even if there is a nice algorithm for rfft, I don't think decomposing to many rffts in a loop would be more efficient than converting this to, say, a convolution with something like `window*exp` (if that is possible with the configurations you are trying to support).

2025-03-28 15:19 UTC, giacs-epic commented
> A general comment before reviewing further:
> 
> Is it absolutely necessary to use a loop? The only times I would ever consider using a loop is if there is a necessary loop-carried dependency, but I don't think that is the case here.
> 
> Even if there is a nice algorithm for rfft, I don't think decomposing to many rffts in a loop would be more efficient than converting this to, say, a convolution with something like `window*exp` (if that is possible with the configurations you are trying to support).

The two approaches have different time complexities: assuming N is both the number of frequency samples and the window length (as per default) and T is the number of frames, STFT via Conv would be O(T N^2), while STFT via many FFTs (Cooley-Tukey algorithm) would be O(T N log2(N)).
Our reference model (Parakeet) for example would have the following settings for STFT when inputting a single signal of 10 seconds:
```
signal = float32[1,160512]
frame_step = 160
window = float32[512]
frame_length = 512
```
For a single core execution the many FFTs would give a ~56x speedup. In a parallel execution setting the Conv-based algorithm would have 1 more axis for parallelization (dimension N=512), so which algorithm wins would be highly dependent on the number of cores available and the signal length (and also the batches dimension).

Regarding the use of a loop, the many FFTs requires it as the signal length dimension could be unknown. If I remember correctly the loop gets unrolled completely in case the signal length dimension is known.

2025-03-28 15:57 UTC, giacs-epic commented on lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
> +    // return final_freq_tensor
Removed in last commit.

2025-03-28 15:57 UTC, giacs-epic commented on lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
> +          rewriter.create<ConstantIntOp>(loc, rewriter.getI64IntegerAttr(4)));
Changed in last commit.

2025-03-28 15:58 UTC, giacs-epic commented on lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
> +                                         "Unsupported: return_complex=False");
Changed in last commit.

2025-04-11 08:46 UTC, giacs-epic commented
@zjgarvey is it ok to merge this or would you like to discuss further?

2025-04-11 13:59 UTC, zjgarvey commented
We can merge it if you want.

There are multiple problems with generating loops instead of linalg ops from torch. IREE's code generation and dispatch formation might have a harder time optimizing around a loop like this (e.g. fusions with other ops).

If you find that IREE doesn't efficiently generate code for this, we can always go back and change it later, too.

2025-04-11 16:13 UTC, zjgarvey approved these changes
This looks good to me. If you notice poor performance or compilation issues (e.g. through IREE) with the loop approach we can always go back and try something else out.

2025-04-11 16:40 UTC, merged

2025-04-16 10:31 UTC, giacs-epic commented on projects/pt1/e2e_testing/xfail_sets.py
> +    "AtenStftCenter2DHopLength3WindowPadBoth_basic",
Yes. I get errors these errors:
```
torch.onnx.errors.SymbolicValueError: STFT does not currently support complex types  [Caused by the value '0 defined in (%0 : Float(2, 32, strides=[32, 1], requires_grad=0, device=cpu) = prim::Param()
```
Except for `AtenStftCenter1DUnkSigLen_basic` and `AtenStftCenter2DWinUnkSize_basic` where I get an error because the unknown dimensions (annotated as `-1` in `spectral.py`) are somehow exported as dimensions of size `1`. E.g. `AtenStftCenter2DWinUnkSize_basic`:
```
RuntimeError: stft(torch.FloatTensor[3, 38], n_fft=7, hop_length=1, win_length=6, window=torch.FloatTensor{[1]}, normalized=0, onesided=1, return_complex=1, align_to_window=None) : expected a 1D window tensor of size equal to win_length=6, but got window with size [1]
```