[cmake] Enable accepting external stablehlo project
llvm/torch-mlir pull request #3927
Opened 2024-12-19 20:25 UTC by shelkesagar29

This MR enables `torch_mlir` project to accept path to external stablehlo and include those directories. This in turn enables `torch_mlir` to be part of bigger compiler project when `stablehlo` is already a
dependency.

2024-12-19 20:26 UTC, shelkesagar29 commented
@powderluv can you please help review?

2024-12-20 03:40 UTC, stellaraccident approved these changes
@marbre for visibility (he was talking about possibly modernizing some of the cmake goo around this)

2024-12-20 10:31 UTC, marbre commented on CMakeLists.txt
> +    include_directories(${TORCH_MLIR_EXTERNAL_STABLEHLO_DIR})
I would have assumed that the external project also makes the includes available.

2024-12-20 10:47 UTC, marbre commented on CMakeLists.txt
> +  else()
Actually
```suggestion
  # Only configure StableHLO if it isn't provided from a top-level project
  if ("${TORCH_MLIR_EXTERNAL_STABLEHLO_DIR}" STREQUAL "")
```
should be sufficient. In that case I would probably replace the string with a boolean as it seems that the string isn't used elsewhere.

Depending on how the super project is set up (and pulls in torch-mlir and stablehlo) we could consider to add a `TORCH_BUILD_EMBEDDED` option, as some parts in the current out-of tree build config might be in responsibility of the super project as well.

2025-01-13 21:09 UTC, shelkesagar29 commented on CMakeLists.txt
> +    include_directories(${TORCH_MLIR_EXTERNAL_STABLEHLO_DIR})
Yes, this is fair assumption.

2025-01-13 21:13 UTC, shelkesagar29 commented on CMakeLists.txt
> +  else()
I have made suggested changes and added a boolean variable `TORCH_MLIR_USE_EXTERNAL_STABLEHLO`, set to OFF by default. As far as I can see, when `TORCH_MLIR_OUT_OF_TREE_BUILD` is enabled, MLIR package is searched by top level cmake.  Top level project can take care of this by passing `MLIR_DIR` and `LLVM_DIR` make options.

2025-01-13 21:26 UTC, shelkesagar29 commented on CMakeLists.txt
> -    $<BUILD_INTERFACE:${MLIR_INCLUDE_DIRS}>
Using `MLIR_INCLUDE_DIRS`  creates an issue where `CMAKE_CURRENT_SOURCE_DIR` is added to include directories of target, leading to error as mentioned here https://stackoverflow.com/questions/76516562/cmake-why-interface-include-directories-can-be-populated-behind-my-back

One can confirm this by getting `INCLUDE_DIRECTORIES` target property of any target in Torch-MLIR.
This somehow created issue only when torch_mlir project is nested in some other project.

Change made here is really NFC since `MLIR_INCLUDE_DIRS ` contains both `MLIR_INCLUDE_DIR ` and `MLIR_GENERATED_INCLUDE_DIR ` but this does resolve source directory being added to include dir issue.

2025-01-13 21:27 UTC, shelkesagar29 commented
@marbre can you double and give it a green light?

2025-01-14 09:33 UTC, marbre requested changes

2025-01-14 09:33 UTC, marbre commented on CMakeLists.txt
> +    include_directories(${CMAKE_CURRENT_SOURCE_DIR}/externals/stablehlo)
```suggestion
  set(STABLEHLO_BUILD_EMBEDDED ON)
  set(STABLEHLO_ENABLE_BINDINGS_PYTHON ON)
  add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/externals/stablehlo
    ${CMAKE_CURRENT_BINARY_DIR}/stablehlo
    EXCLUDE_FROM_ALL)
  include_directories(${CMAKE_CURRENT_SOURCE_DIR}/externals/stablehlo)
```
To keep it consistent the indent should be as before thus effectively only changing the if condition.

2025-01-14 18:44 UTC, shelkesagar29 commented on CMakeLists.txt
> +    include_directories(${CMAKE_CURRENT_SOURCE_DIR}/externals/stablehlo)
Done. Thanks for pointing it out.

2025-01-14 19:33 UTC, marbre approved these changes
Thanks!

2025-01-14 19:33 UTC, marbre commented on CMakeLists.txt
> -    $<BUILD_INTERFACE:${MLIR_INCLUDE_DIRS}>
Not following in depth here but this should be fine if the build passes.

2025-01-14 19:37 UTC, merged