[MLIR][TORCH] Add E2E support for `aten.mul.Scalar` and `aten.addmm`
llvm/torch-mlir pull request #412
Opened 2021-11-11 09:10 UTC by Shukla-Gaurav

This commit adds lowering of `aten.mul.Scalar` and also adds
decomposition of `aten.addmm` to `aten.mul.Scalar`, `aten.add.Tensor`
and `aten.mm` ops.

Signed-Off-by: Gaurav Shukla <gaurav@nod-labs.com>

2021-11-11 14:17 UTC, pashu123 approved these changes
LGTM!

2021-11-11 15:03 UTC, ramiro050 requested changes
Good job! A few comment below

2021-11-11 15:10 UTC, Shukla-Gaurav commented on e2e_testing/torchscript/basic.py
> +        return torch.addmm(M, mat1, mat2, beta=0.0, alpha=1.0)
Thanks, that's a good point. I will update this.

2021-11-11 15:11 UTC, Shukla-Gaurav commented on lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
> +    if (getTensorRank(input) != 2 || getTensorRank(mat1) != 2 ||
I see. I missed this, will update accordingly.

2021-11-17 19:37 UTC, cathyzhyi approved these changes

2021-11-18 16:43 UTC, Shukla-Gaurav commented
Thanks @ramiro050 for spotting broadcastable case. It's fixed now. Can you please review again?

2021-11-18 16:53 UTC, ramiro050 commented
Awesome! LGTM!

2021-11-18 16:56 UTC, merged