[WIP] This is a basic splitting of TorchToLinalg.cpp.
llvm/torch-mlir pull request #443
Opened 2021-11-25 12:13 UTC by pashu123

Before this file gets even larger let's split it.

1. I am yet to write all the common functions under a namespace.
2. Unfortunately, the conversion is giving seg fault. Have to debug.

2021-11-25 12:15 UTC, pashu123 commented
@cathyzhyi I have started to split files in torchToLinalg.cpp. Initial suggestion needed.

2021-11-25 12:16 UTC, pashu123 commented
@ramiro050 Any suggestions?

2021-11-29 16:29 UTC, cathyzhyi commented
This is a really good starting point! Thanks for making the changes.
Can you refer to the original issue in the comment so that people not familiar with this would know the background. 

> I am yet to write all the common functions under a namespace

yea, we will need to put them under torch namespace.

> All the common functions should go to Utils.h under utils dir or CommonTorchToLinalg.h like we have in this PR?

I think `CommonTorchToLinalg.h` as it is is fine.

Is the current plan using one .cpp file for just one pattern? I think we can probably just put all math related ops into one file and use `populateLoweringMathOpPattern` to populate all of them together. 

@silvasean Do you have any suggestions on how to split the file?

2021-11-29 16:38 UTC, pashu123 commented
> This is a really good starting point! Thanks for making the changes. Can you refer to the original issue in the comment so that people not familiar with this would know the background.
> 
> > I am yet to write all the common functions under a namespace
> 
> yea, we will need to put them under torch namespace.
> 
> > All the common functions should go to Utils.h under utils dir or CommonTorchToLinalg.h like we have in this PR?
> 
> I think `CommonTorchToLinalg.h` as it is is fine.
> 
> Is the current plan using one .cpp file for just one pattern? I think we can probably just put all math related ops into one file and use `populateLoweringMathOpPattern` to populate all of them together.
> 
> @silvasean Do you have any suggestions on how to split the file?

@cathyzhyi Yes, we put all math-related ops into one file and use `populateLoweringMathOp..` as suggested. We can have elementwise, math, reduction etc as different categories. We can pull out ops from torchTolinalg and put them into this scheme incrementally. The original issue is here: https://github.com/llvm/torch-mlir/issues/382

2021-11-29 16:54 UTC, cathyzhyi requested changes

2021-11-29 16:54 UTC, cathyzhyi commented on include/torch-mlir/Conversion/TorchToLinalg/CommonTorchToLinalg.h
> +#ifndef TORCH_COMMON_MLIR_CONVERSION_ATENTOLINALG_ATENTOLINALG_H
We need license headers for all the new files.

2021-11-30 04:53 UTC, pashu123 commented
@silvasean: I and @cathyzhyi had a small discussion yesterday and we have two possible layouts:-
1. Put every op lowering in one file under generalized dir: For eg., Under the `view` directory we can have transpose.cpp, permute.cpp, reshape.cpp files containing respective op lowerings.
2. Put ops that share a similar logic in a single file under a generalized dir, for eg., transpose.cpp and permute.cpp share a similar logic and hence their lowering can be put into a single cpp file inside `view` dir. Similarly, aten::mat.mul, aten::linear, aten::bmm op lowering can be put into a single cpp file under `math` or `reduce` dir.

2021-11-30 20:20 UTC, silvasean commented
I would prefer option 2. Option 1 is a bit too fine-grained, and is not well-defined when multiple ops share lots of common functionality.

We should break it into coarse categories, that are easy for people to guess which file a particular op is in.

I gave a suggested splitting in https://github.com/llvm/torch-mlir/issues/382#issue-1036924035, but I'm not attached to that. Anything that seems reasonable is fine for now. This is mostly about code sharing, without being too confusing.

Thanks for doing this :)

2022-03-15 15:39 UTC, Shukla-Gaurav commented
This is now covered by https://github.com/llvm/torch-mlir/pull/657. @pashu123 I think we should close this.

2022-03-16 19:44 UTC, closed without merging