[TORCH][MLIR] Templatize lowering of [`aten.zeros|aten.ones|aten.empty`] ops
llvm/torch-mlir pull request #474
Opened 2021-12-12 19:01 UTC by Shukla-Gaurav

- Templatize `aten.zeros` and `aten.ones` ops lowering.
- Add E2E support for `aten.empty` op.
- Add Integer type support in `aten.mul.Scalar` op lowering.

Signed-Off-by: Gaurav Shukla <gaurav@nod-labs.com>

2021-12-12 19:40 UTC, pashu123 requested changes

2021-12-12 19:40 UTC, pashu123 commented on lib/Conversion/TorchToLinalg/TorchToLinalg.cpp
> +    } else {
Please check for type, there may be types other than float and integer. https://pytorch.org/docs/stable/tensors.html

2021-12-12 19:40 UTC, pashu123 commented on lib/Conversion/TorchToLinalg/TorchToLinalg.cpp
> +    auto getConstant = [&](int64_t val, Type elemType) -> Value {
This is a very generic function and can share functionalities across many functions. Instead of a lambda can be placed outside as a static function.

2021-12-12 19:40 UTC, pashu123 commented on e2e_testing/torchscript/basic.py
> +        return torch.abs(torch.empty((3, 4), dtype=torch.float32, pin_memory=False)) > -1.0
Nit: Please format your python code.

2021-12-12 19:40 UTC, pashu123 commented on lib/Conversion/TorchToLinalg/TorchToLinalg.cpp
> +    } else {
Add a test case where types are not the same i.e., `torch.mul(x, 4.0)` where x is torch.int64.

2021-12-13 14:51 UTC, pashu123 approved these changes
Great effort! LGTM.

2021-12-13 18:37 UTC, merged

2021-12-13 19:22 UTC, Shukla-Gaurav commented
@silvasean This PR uses a C++17 feature `if constexpr ()`. Should I fix this right away in a follow-up PR or Is it okay to leave it as it is? cc: @ramiro050

2021-12-14 00:29 UTC, silvasean commented
I would avoid `if constexpr`. In this case, I would recommend to not use a template for this. Just pass `Operation *op` -- you can still `dyn_cast`/`isa`.