[MLIR][TORCH] Add E2E support for aten.arange, aten.arange.start, ate…
llvm/torch-mlir pull request #501
Opened 2021-12-23 13:28 UTC by vivekkhandelwal1

…n.arange.start_step op

This commit adds lowering of `aten.arange.start_step` op.
This commit decomposes `aten.arange` and `aten.arange.start` into `aten.arange.start_step` op.

Signed-Off By: Vivek Khandelwal <vivek@nod-labs.com>

2021-12-23 14:03 UTC, pashu123 requested changes

2021-12-23 17:04 UTC, gprateek93 reviewed
Nice work. One minor comment.

2021-12-23 17:22 UTC, ramiro050 requested changes
Thanks for this! A few comments below

2021-12-23 17:22 UTC, ramiro050 commented on lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
> +    if (isa<AtenArangeStartOp>(op)) {
I'm always a bit unsure about combining templates and dynamic casts. The main advantage of a template is that it allows compile time polymorphism (which can have a speed benefit), but the dynamic cast counteracts the benefit by requiring type information during runtime. 

One way of avoiding this issue is to have the template be a helper function that takes as arguments the `op` and the `start` value, then the two classes for decomposing `aten.arange` and `aten.arange.start` can call this function. In other words, we are abstracting too early. What the two ops have in common is not the decomposition, but the decomposition once the `start` value has been determined

2021-12-27 16:42 UTC, ramiro050 approved these changes
Thanks for this. LGTM!

2021-12-27 17:15 UTC, merged