Refine static shapes for return tensors of conv2d and maxpool2d
llvm/torch-mlir pull request #502
Opened 2021-12-27 16:11 UTC by ljfitz

In RefineTypes.cpp, the return `dtype` was being determined for conv2d and maxpool2d, but the shape was not. This code adds static shape computation then the operator arguments provide the required static details.

This may relate to/clash with other possible approaches to #415, where @silvasean talks about revamping shape inference to be more precise, but I don't know what @silvasean had in mind.

2021-12-28 16:24 UTC, ramiro050 requested changes
Thanks for this! Everything looks good to me, I just have a small style comment below

2021-12-28 16:24 UTC, ramiro050 commented on lib/Dialect/Torch/Transforms/RefineTypes.cpp
> +//  floor((dim_in + 2 * padding - dilation * (kernelSize - 1) - 1) / stride) + 1
Nit: I don't think this is necessary since this information can very easily be determined from the body of the function

2021-12-28 16:39 UTC, ramiro050 reviewed
Oh also, given that the size calculations are really complicated, it would be nice to have an e2e test with static shapes to make sure our code agrees with PyTorch

https://github.com/llvm/torch-mlir/blob/main/e2e_testing/torchscript/conv.py

2021-12-29 09:43 UTC, ljfitz commented
> e2e test with static shapes

Thanks @ramiro050 for the review and the suggestion. I've added an e2e test and manually verified that the output of `torchscript-module-to-torch-backend-pipeline` has information being propagated as expected.

2022-01-03 15:05 UTC, ramiro050 approved these changes
LGTM! Thanks for adding this!

2022-01-03 15:14 UTC, ljfitz commented
> LGTM! Thanks for adding this!

And thanks for the supportive review. I see that I haven't permission to merge the the pull request. Do you know if merging will happen automatically or if I need to take some additional action?

2022-01-03 17:09 UTC, merged

2022-01-03 17:10 UTC, ramiro050 commented
> And thanks for the supportive review. I see that I haven't permission to merge the the pull request. Do you know if merging will happen automatically or if I need to take some additional action?

Merged!