* [tosa] Support for AtenFlattenUsingIntsOp
llvm/torch-mlir pull request #548
Opened 2022-01-28 17:12 UTC by anupgangwar

Signed-off-by: Anup Gangwar <anup.gangwar@arm.com>

2022-01-28 17:13 UTC, anupgangwar commented
Summary:
    Passed: 65
    Expectedly Failed: 187

Tagging @cathyzhyi for review.

2022-01-28 18:38 UTC, sjarus commented
Thank you for these fixes @ljfitz and @cathyzhyi! I'm looking forward to trying this out with my maxpool/adaptive avgpool TOSA implementations once it's merged.

2022-01-28 22:08 UTC, cathyzhyi requested changes

2022-01-28 22:08 UTC, cathyzhyi commented on lib/Conversion/TorchToTosa/TorchToTosa.cpp
> +  for (auto s : selfType.getShape()) {
nit: could use llvm::enumerate() for this, then the var `idx` would not be needed. see example here https://github.com/llvm/mlir-npcomp/blob/52ed3313b49b8f56a6dac270ee334c6dffebcaf2/lib/Conversion/TorchToLinalg/TorchToLinalg.cpp#L2886

2022-01-28 22:08 UTC, cathyzhyi commented on lib/Conversion/TorchToTosa/TorchToTosa.cpp
> +      op->getLoc(), getTypeConverter()->convertType(newType), adaptor.self(),
newType is already builtin tensor type and the type conversion is not needed.

2022-01-29 02:23 UTC, cathyzhyi approved these changes

2022-01-29 05:38 UTC, merged