[tosa] Add maxpool2d and adaptive_avgpool2d support
llvm/torch-mlir pull request #550
Opened 2022-01-28 22:20 UTC by sjarus

Signed-off-by: Suraj Sudhir <suraj.sudhir@arm.com>

2022-01-28 22:29 UTC, sjarus commented
Testing: 

Both e2e tests pass with shapes made static: 

****** Unexpectedly Passed tests - 2 tests
    XPASS - "AdaptiveAvgPool2dModule_basic"
    XPASS - "MaxPool2dModule_basic"

A very large unit test suite also passes all permutations of inputs given: 

Results PASS test_adaptive_avgpool2d_1x1x16x16_f32_out1x1
Results PASS test_adaptive_avgpool2d_1x1x16x16_f32_out1x8
Results PASS test_adaptive_avgpool2d_1x1x16x16_f32_out1x16
Results PASS test_adaptive_avgpool2d_1x1x16x16_f32_out8x1
Results PASS test_adaptive_avgpool2d_1x1x16x16_f32_out8x8
Results PASS test_adaptive_avgpool2d_1x1x16x16_f32_out8x16
Results PASS test_adaptive_avgpool2d_1x1x16x16_f32_out16x1
Results PASS test_adaptive_avgpool2d_1x1x16x16_f32_out16x8
Results PASS test_adaptive_avgpool2d_1x1x16x16_f32_out16x16
Results PASS test_adaptive_avgpool2d_5x2x32x32_f32_out1x1
Results PASS test_adaptive_avgpool2d_5x2x32x32_f32_out1x16
Results PASS test_adaptive_avgpool2d_5x2x32x32_f32_out1x32
Results PASS test_adaptive_avgpool2d_5x2x32x32_f32_out16x1
Results PASS test_adaptive_avgpool2d_5x2x32x32_f32_out16x16
Results PASS test_adaptive_avgpool2d_5x2x32x32_f32_out16x32
Results PASS test_adaptive_avgpool2d_5x2x32x32_f32_out32x1
Results PASS test_adaptive_avgpool2d_5x2x32x32_f32_out32x16
Results PASS test_adaptive_avgpool2d_5x2x32x32_f32_out32x32
Results PASS test_maxpool2d_3x3_1x1x16x16_f32_st11_pad00
Results PASS test_maxpool2d_3x3_1x1x16x16_f32_st12_pad00
Results PASS test_maxpool2d_3x3_1x1x16x16_f32_st21_pad00
Results PASS test_maxpool2d_3x3_1x1x16x16_f32_st22_pad00
Results PASS test_maxpool2d_3x3_5x2x32x32_f32_st11_pad00
Results PASS test_maxpool2d_3x3_5x2x32x32_f32_st12_pad00
Results PASS test_maxpool2d_3x3_5x2x32x32_f32_st21_pad00
Results PASS test_maxpool2d_3x3_5x2x32x32_f32_st22_pad00
Results PASS test_maxpool2d_5x5_1x1x16x16_f32_st11_pad00
Results PASS test_maxpool2d_5x5_1x1x16x16_f32_st11_pad01
Results PASS test_maxpool2d_5x5_1x1x16x16_f32_st11_pad10
Results PASS test_maxpool2d_5x5_1x1x16x16_f32_st11_pad11
Results PASS test_maxpool2d_5x5_1x1x16x16_f32_st12_pad00
Results PASS test_maxpool2d_5x5_1x1x16x16_f32_st12_pad01
Results PASS test_maxpool2d_5x5_1x1x16x16_f32_st12_pad10
Results PASS test_maxpool2d_5x5_1x1x16x16_f32_st12_pad11
Results PASS test_maxpool2d_5x5_1x1x16x16_f32_st21_pad00
Results PASS test_maxpool2d_5x5_1x1x16x16_f32_st21_pad01
Results PASS test_maxpool2d_5x5_1x1x16x16_f32_st21_pad10
Results PASS test_maxpool2d_5x5_1x1x16x16_f32_st21_pad11
Results PASS test_maxpool2d_5x5_1x1x16x16_f32_st22_pad00
Results PASS test_maxpool2d_5x5_1x1x16x16_f32_st22_pad01
Results PASS test_maxpool2d_5x5_1x1x16x16_f32_st22_pad10
Results PASS test_maxpool2d_5x5_1x1x16x16_f32_st22_pad11
Results PASS test_maxpool2d_5x5_5x2x32x32_f32_st11_pad00
Results PASS test_maxpool2d_5x5_5x2x32x32_f32_st11_pad01
Results PASS test_maxpool2d_5x5_5x2x32x32_f32_st11_pad10
Results PASS test_maxpool2d_5x5_5x2x32x32_f32_st11_pad11
Results PASS test_maxpool2d_5x5_5x2x32x32_f32_st12_pad00
Results PASS test_maxpool2d_5x5_5x2x32x32_f32_st12_pad01
Results PASS test_maxpool2d_5x5_5x2x32x32_f32_st12_pad10
Results PASS test_maxpool2d_5x5_5x2x32x32_f32_st12_pad11
Results PASS test_maxpool2d_5x5_5x2x32x32_f32_st21_pad00
Results PASS test_maxpool2d_5x5_5x2x32x32_f32_st21_pad01
Results PASS test_maxpool2d_5x5_5x2x32x32_f32_st21_pad10
Results PASS test_maxpool2d_5x5_5x2x32x32_f32_st21_pad11
Results PASS test_maxpool2d_5x5_5x2x32x32_f32_st22_pad00
Results PASS test_maxpool2d_5x5_5x2x32x32_f32_st22_pad01
Results PASS test_maxpool2d_5x5_5x2x32x32_f32_st22_pad10
Results PASS test_maxpool2d_5x5_5x2x32x32_f32_st22_pad11

2022-01-31 05:51 UTC, sjarus commented
With a few changes to RefineTypes to be released separately, this also passes static shaped ResNet18 - the first full network on TorchToTosa: 

$ ./tools/torchscript_e2e_test.sh --config=tosa --filter=ResNet18StaticModule_basic -v
PASS - "ResNet18StaticModule_basic"

Summary:
    Passed: 1

2022-01-31 16:34 UTC, cathyzhyi requested changes
Looks good other than a few comments.

2022-01-31 16:34 UTC, cathyzhyi commented on lib/Conversion/TorchToTosa/TorchToTosa.cpp
> +                        Value input, SmallVector<int32_t> transposeDims) const {
it's recommended to use ArrayRef if the list is not modified. refer to https://llvm.org/docs/ProgrammersManual.html#llvm-adt-smallvector-h

2022-01-31 16:34 UTC, cathyzhyi commented on lib/Conversion/TorchToTosa/TorchToTosa.cpp
> +            OpConversionPattern<AtenOpT>::getTypeConverter()->convertType(
`transposedInputType ` is built in tensor type already so the type conversion is not needed.

2022-01-31 16:34 UTC, cathyzhyi commented on lib/Conversion/TorchToTosa/TorchToTosa.cpp
> +                                ConversionPatternRewriter &rewriter) const {
need to mark `override`

2022-01-31 16:34 UTC, cathyzhyi commented on lib/Conversion/TorchToTosa/TorchToTosa.cpp
> +    if (!(inputTy.getRank() == 4) && !(inputRank == 3))
nit: inputTy.getRank != 4 and inputRank != 3

2022-01-31 16:34 UTC, cathyzhyi commented on lib/Conversion/TorchToTosa/TorchToTosa.cpp
> +    if (!(inputTy.getRank() == 4) && !(inputRank == 3))
nit: inputTy.getRank() != 4 and inputRank != 3

2022-01-31 20:01 UTC, sjarus commented
@cathyzhyi I've tried to duplicate the failure locally but am unable to do so - it passes e2e locally. Is there something obvious I'm missing here ?

2022-01-31 20:27 UTC, cathyzhyi commented on lib/Conversion/TorchToTosa/TorchToTosa.cpp
> +  LogicalResult processInputs(AtenOpT op, OpAdaptor adaptor,
need `override` here as well

2022-01-31 20:28 UTC, cathyzhyi commented
> @cathyzhyi I've tried to duplicate the failure locally but am unable to do so - it passes e2e locally. Is there something obvious I'm missing here ?

hmmm, it's not obvious to me. Let me try on my machine.

2022-01-31 20:31 UTC, cathyzhyi commented on lib/Conversion/TorchToTosa/TorchToTosa.cpp
> +    ArrayRef<int32_t> nchwToNhwc4DTransposeDims({0, 2, 3, 1});
oh, you still need to use SmallVector here. ArrayRef won't keep the integer aline.

2022-01-31 21:17 UTC, sjarus commented
Passes now, thanks for that ArrayRef catch. Also found another missing override I added - the build has no warnings now.

2022-01-31 21:25 UTC, cathyzhyi approved these changes

2022-01-31 21:34 UTC, merged