* [tosa] Support for AtenNe[Tensor|Scalar]Op, AtenLog2Op,
llvm/torch-mlir pull request #575
Opened 2022-02-10 16:15 UTC by anupgangwar

AtenBitwiseAndTensorOp, AtenSquareOp and AtenThresholdOp
* Fix for Issue #532 - Mixed input types for few ops and updated few
tests to use i32 instead of i64

Signed-off-by: Anup Gangwar <anup.gangwar@arm.com>

2022-02-11 03:59 UTC, cathyzhyi requested changes

2022-02-11 03:59 UTC, cathyzhyi commented on lib/Conversion/TorchToTosa/TorchToTosa.cpp
> +                                           /* shift */ 0);
nit: the convention is /*shift=*/. Refer to https://llvm.org/docs/CodingStandards.html#comment-formatting

2022-02-11 03:59 UTC, cathyzhyi commented on lib/Conversion/TorchToTosa/TorchToTosa.cpp
> +                                      alphaTensor, outElemTy, false))) {
nit: comment for `false`

2022-02-11 03:59 UTC, cathyzhyi commented on lib/Conversion/TorchToTosa/TorchToTosa.cpp
> +        static_cast<mlir::Type>(
nit: `mlir::` is not needed.

2022-02-11 03:59 UTC, cathyzhyi commented on lib/Conversion/TorchToTosa/TorchToTosa.cpp
> +        static_cast<mlir::Type>(
nit: `mlir::` is not needed.

2022-02-11 03:59 UTC, cathyzhyi commented on lib/Conversion/TorchToTosa/TorchToTosa.cpp
>        if (failed(torchScalarToTosaTensor(rewriter, op.getOperation(),
nit: we can pass `op` without using `getOperation`. Could you also fix other places in this file as well.

2022-02-11 04:01 UTC, cathyzhyi commented
Can you also fix the commit message? The first line is the tile and there need to be a space line between the title line and summary.

2022-02-11 11:53 UTC, ljfitz commented on lib/Conversion/TorchToTosa/TorchToTosa.cpp
> +  auto is_float =
nit: camelBack is being used in this file so `isFloat` would be more consistent.

2022-02-11 17:28 UTC, cathyzhyi requested changes

2022-02-11 18:53 UTC, anupgangwar commented on lib/Conversion/TorchToTosa/TorchToTosa.cpp
> +      int32_t d = isFloat ? static_cast<int32_t>(doubleValue)
The variable is used right on the next line so not sure I agree.

2022-02-11 18:53 UTC, anupgangwar commented on lib/Conversion/TorchToTosa/TorchToTosa.cpp
> +      if ((isFloat && doubleValue > std::numeric_limits<int32_t>::max()) ||
Good point, will refactor into a function and check both the bounds.

2022-02-11 19:02 UTC, cathyzhyi commented on lib/Conversion/TorchToTosa/TorchToTosa.cpp
> +      int32_t d = isFloat ? static_cast<int32_t>(doubleValue)
yea, that's probably fine.

2022-02-11 20:09 UTC, cathyzhyi approved these changes
Thanks!

2022-02-11 20:30 UTC, merged

2022-02-14 16:13 UTC, cathyzhyi commented on lib/Conversion/TorchToTosa/TorchToTosa.cpp
> +      if ((isFloat && doubleValue > std::numeric_limits<int32_t>::max()) ||
@anupgangwar Hey Anup, seems there are some compilation warning caused by the `isInValidRange` helper. Could you fix this?

2022-02-14 16:41 UTC, cathyzhyi commented on lib/Conversion/TorchToTosa/TorchToTosa.cpp
> +      if ((isFloat && doubleValue > std::numeric_limits<int32_t>::max()) ||
It's this one from the CI output
```
implicit conversion from 'long' to 'double' changes value from 9223372036854775807 to 9223372036854775808 [-Wimplicit-const-int-float-conversion]
           (doubleValue <= std::numeric_limits<T>::max());
                        ~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/torch-mlir/torch-mlir/lib/Conversion/TorchToTosa/TorchToTosa.cpp:163:12: note: in instantiation of function template specialization '(anonymous namespace)::isInValidRange<long>' requested here
      if (!isInValidRange<int64_t>(isFloat, doubleValue, isInt, intValue)) {
           ^
```