Add optional int list ODS type
llvm/torch-mlir pull request #643
Opened 2022-03-04 05:11 UTC by gpetters94

2022-03-04 15:44 UTC, cathyzhyi requested changes

2022-03-04 15:44 UTC, cathyzhyi commented on python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
> +    "int[]?": "TorchOptionalIntListType",
There is some confusion in naming. "Tensor?[]": "AnyTorchOptionalTensorListType" means the tensor element is optional but "int[]?": "TorchOptionalIntListType" means the list is optional.

Can you help to change all list type to ListOfXXXType. Optional list type becomes OptionalListOfXXXType and when list element is optional ListOfOptionalXXXType.

2022-03-31 00:03 UTC, gpetters94 commented
Are these names acceptable? Some of them are kind of unwieldy.

2022-04-04 15:20 UTC, cathyzhyi commented
@silvasean Hey Sean, do you have any comments on the names? This is for addressing https://github.com/llvm/torch-mlir/pull/643#discussion_r819681492 to make the difference between `Tensor[]?` and `Tensor?[]`

2022-04-04 17:26 UTC, silvasean commented
Following ODS conventions I think we should call these `AnyTorch*` (except the ones that are `Torch_X` naturally). So I would go with `Tensor[]?` as `AnyTorchOptionalListOfTensorType` and `Tensor?[]` as `AnyTorchListOfOptionalTensorType` (and `Tensor?[]?` would be `AnyTorchOptionalListOfOptionalTensorType`). I think the important thing is that they read left-to-right directly and consistently (so you just reverse the reading of the torch type string: `Tensor[]?` -> `Tensor, [], ?` --(reverse)--> `?, [], Tensor` -> `AnyTorchOptionalListOfTensorType`)

2022-04-05 15:12 UTC, cathyzhyi approved these changes

2022-04-07 17:27 UTC, silvasean commented on python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
> +    "int[]": "ListOfTorchIntType",
AnyTorchListOfIntType

2022-04-07 17:27 UTC, silvasean commented on python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
>      "int?": "TorchOptionalIntType",
AnyTorchOptionalIntType

2022-04-07 17:27 UTC, silvasean commented on python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
> +    "int[]?": "OptionalListOfTorchIntType",
AnyTorchOptionalListOfIntType

2022-04-07 18:48 UTC, cathyzhyi commented
@gpetters94 the change looks good. You can go ahead and merge when you are ready.

2022-04-07 22:15 UTC, merged