[MLIR][TORCH] Add value tensor variant to aten::copy_ op
llvm/torch-mlir pull request #676
Opened 2022-03-16 15:26 UTC by vivekkhandelwal1

This commit adds the op `ValsemVariantAtenCopyOp` that represents
`AtenCopy_Op` without the underscore. This is needed to make sure
that the `ReduceOpVariants` pass turns the in-place op into an op
that takes value tensors as inputs, otherwise the
`MaximizeValueSemantics` pass will not be able to add value
semantics correctly.

This commit also adds the lowering of `ValsemVariantAtenCopyOp`.

Signed-Off By: Vivek Khandelwal <vivek@nod-labs.com>

2022-03-16 16:49 UTC, ramiro050 requested changes
Thanks for refactoring the broadcast code!

2022-03-16 16:49 UTC, ramiro050 commented on lib/Conversion/TorchToLinalg/DataMovement.cpp
> +  if (broadcastToShape.size() < inputShape.size())
`if` needs curly braces

2022-03-16 16:49 UTC, ramiro050 commented on lib/Conversion/TorchToLinalg/DataMovement.cpp
> +broadcastToGivenShape(OpTy op, ConversionPatternRewriter &rewriter, Value input,
I don't think this needs to be a template. I also noticed that there is nothing in the body of the function that requires information about the `op`. The `op` is only used to get a location and a context, however you can get a context from the rewriter itself. Here, I would use a similar signature to other helper functions

```cpp
broadcastToGivenShape(PatternRewriter &rewriter, Location loc, ...)
```

This makes it clear to the user that what this function does is `op`-independent.

2022-03-16 16:49 UTC, ramiro050 commented on lib/Conversion/TorchToLinalg/DataMovement.cpp
> +    if (failed(broadcastToGivenShape<ValsemVariantAtenCopyOp>(
`if` needs curly braces

2022-03-16 17:08 UTC, ramiro050 commented on lib/Conversion/TorchToLinalg/DataMovement.cpp
> +broadcastToGivenShape(OpTy op, ConversionPatternRewriter &rewriter, Value input,
Never mind, you do need the `op` as an argument to create the `notifyMatchFailure`. So you should keep the signature unchanged. However, I would remove the template code and pass the `op` as `Operation *op`.

2022-03-17 17:48 UTC, ramiro050 approved these changes
LGTM! Just one small comment

2022-03-21 10:52 UTC, pashu123 approved these changes
LGTM!

2022-03-21 13:42 UTC, merged