Make e2e testing parallel
llvm/torch-mlir pull request #736
Opened 2022-04-04 20:13 UTC by cathyzhyi

This change makes the e2e testing parallel using the multiprocessing
python module.

This also fixes the inplace update tensor issue we had
where the torchscript execution would update the input value inplace
resulting the actual test not being able to see the original input
value.

2022-04-04 20:40 UTC, silvasean requested changes

2022-04-04 20:40 UTC, silvasean commented on python/torch_mlir_e2e_test/torchscript/framework.py
> +# unknown reason when passed through the shared memory through synchornized
typo synchronized

2022-04-04 20:40 UTC, silvasean commented on python/torch_mlir_e2e_test/torchscript/framework.py
> +def clone_torchscriptvalue(v: TorchScriptValue):
nit: clone_torch_script_value for consistency

2022-04-04 20:40 UTC, silvasean commented on python/torch_mlir_e2e_test/torchscript/framework.py
> +def compile_and_run_test(test_name: str, results: mp.Queue, tests: Dict[str, Test],
nit: can you change this function to have a signature `compile_and_run_test(test: Test, config: TestConfig) -> TestResult` (that knows nothing about parallelism/etc.? And then inline the other parts of this function into `def worker` below.

2022-04-04 20:40 UTC, silvasean commented on python/torch_mlir_e2e_test/torchscript/framework.py
> +    NUMBER_OF_PROCESSES = min(mp.cpu_count(), task_queue.qsize())
Usually it is good to have slightly more processes than CPU's. So maybe something like `int(mp.cpu_count() * 1.1)` or something.

2022-04-04 20:40 UTC, silvasean commented on python/torch_mlir_e2e_test/torchscript/framework.py
> +    manager = mp.Manager()
Can you add a comment here describing the overall strategy.

2022-04-04 20:40 UTC, silvasean commented on python/torch_mlir_e2e_test/torchscript/framework.py
> +    run_tasks_in_parrallel(tests_queue, worker)
typo: parallel

2022-04-04 20:40 UTC, silvasean commented on python/torch_mlir_e2e_test/torchscript/framework.py
> +        for test_name in iter(q.get, 'STOP'):
nit: `"QUEUE_SENTINEL"` to make it more obvious (also, for consistency, use `"`)

2022-04-04 20:40 UTC, silvasean commented on python/torch_mlir_e2e_test/torchscript/framework.py
> +    sync_results = manager.list()
why is this list instead of queue? The signature of compile_and_run_test says `mp.Queue`.

2022-04-04 20:40 UTC, silvasean commented on python/torch_mlir_e2e_test/torchscript/framework.py
> +    all_tests = { test.unique_name for test in tests }
nit: no spaces in `{...}`"  `{test.unique_name for test in tests}`

2022-04-04 20:40 UTC, silvasean commented on python/torch_mlir_e2e_test/torchscript/framework.py
> +    aborted_tests = [
nit: create a new variable here `aborted_test_results`

2022-04-04 20:40 UTC, silvasean commented on python/torch_mlir_e2e_test/torchscript/framework.py
> +            "Testing process terminated. This is mostly likely because of hitting runtime assertion.\n",
Is there a way to get the stdout of the failing process? I'm thinking what the debugging flow will be if there is a crash -- how do we see the error / repro / debug it?

Also, most crashes I have seen happen inside the compiler (failed `cast<>`, missing case in the importer, failed `assert`, ...). Maybe say "Either the compiler crashed or the compiled code crashed at runtime."

2022-04-04 20:40 UTC, silvasean commented on python/torch_mlir_e2e_test/torchscript/framework.py
> +                        compilation_error=None,
nit: is this formatted?

2022-04-05 21:16 UTC, silvasean commented on python/torch_mlir_e2e_test/torchscript/framework.py
> +            "Testing process terminated. This is mostly likely because of hitting runtime assertion.\n",
Okay, that seems acceptable for now.

2022-04-05 21:18 UTC, silvasean approved these changes

2022-04-05 21:18 UTC, silvasean commented on python/torch_mlir_e2e_test/torchscript/framework.py
> +    # TODO: find a clean way to capture the output from crashed process and
nit: capitalize Find.

2022-04-06 15:35 UTC, cathyzhyi commented
hmm, it seems with multiprocess library the CI build takes longer to finish 30m vs 2m for refbackend tests.

2022-04-06 15:37 UTC, cathyzhyi commented
Anyway I can investigate the issue on CI machines directly? On my local machine, it's 4m(after change) vs 45mins(before change) as expected.

2022-04-07 17:33 UTC, silvasean commented
I think the CI machines have only 2 cores. It might be possible to reproduce by limiting to 2 cores locally.

But no, I haven't found a way to easily reproduce the CI runs except by pushing new commits to PR's.

> On my local machine, it's 4m(after change) vs 45mins(before change) as expected.

What was taking 45 minutes before this change?

2022-04-07 18:17 UTC, cathyzhyi commented
> What was taking 45 minutes before this change?

running all the e2e tests with refbackend on my local machine takes 45mins before this change.

2022-04-07 19:55 UTC, silvasean commented
> > What was taking 45 minutes before this change?
> 
> running all the e2e tests with refbackend on my local machine takes 45mins before this change.

Interesting... does this include heavydep tests as well? I think it takes <5 minutes on my local machine (without heavydep). And the CI machines take ~2 min (w/o heavydep), and they are very slow.

2022-05-06 01:27 UTC, merged