Update README.md
llvm/torch-mlir pull request #785
Opened 2022-04-22 21:14 UTC by powderluv

Add a link to pre-built binaries. The binaries pull in the relevant version of torch too.

2022-04-25 14:09 UTC, silvasean requested changes

2022-04-25 19:48 UTC, powderluv commented on README.md
> +load image from https://upload.wikimedia.org/wikipedia/commons/2/26/YellowLabradorLooking_new.jpg
This is the output from the examples/torchscript_resnet18.py script. We can change that if required.

2022-04-25 19:51 UTC, powderluv commented on README.md
> +wget https://raw.githubusercontent.com/llvm/torch-mlir/main/examples/torchscript_resnet18.py
None of the other commands in the README.md have a $ in front. Please let me know if you want me to update all the commands with $ this keeps it consistent with what is there right now.

2022-04-26 08:46 UTC, silvasean commented on README.md
> +wget https://raw.githubusercontent.com/llvm/torch-mlir/main/examples/torchscript_resnet18.py
Oh, that's fine then.

2022-04-26 08:46 UTC, silvasean approved these changes

2022-04-26 14:19 UTC, merged