Ashay/mean reduction
llvm/torch-mlir pull request #809
Opened 2022-04-28 06:19 UTC by ashay

This PR contains commits for adding support for lowering AtenMeanDimOp operations.  Although this PR contains multiple commits (to aid readability), I will squash them into a single commit before merging, if approved.

Perhaps the last two commits in this PR are the best places to start to understand the key approach of these commits.

2022-04-28 13:43 UTC, silvasean commented
Meta-question: @ashay, are you trying to compile a particular model and finding these ops missing? If it is open-source, I would love if we could add it to https://github.com/llvm/torch-mlir/tree/main/build_tools/torchscript_e2e_heavydep_tests so it is easy for us to collaborate on it / burn down the issues.

2022-04-28 13:45 UTC, silvasean requested changes

2022-04-28 15:02 UTC, Shukla-Gaurav commented
Hi @ashay, `aten.mean.dim` op has been addressed here https://github.com/llvm/torch-mlir/pull/613. It's been quite long(I should have fixed that long ago). In that PR the op has been addressed in as a part of decomposition. How should we go ahead?

2022-05-05 17:18 UTC, ashay commented
Closing because #613 addresses adds the required support.

2022-05-05 17:18 UTC, closed without merging