[MLIR][TORCH] Add heavydep tests for Bart, BigBird, and GPT2 model
llvm/torch-mlir pull request #816
Opened 2022-04-29 14:49 UTC by vivekkhandelwal1

This commit adds e2e heavydep tests for Bart, BigBird, and GPT2 model
via AOT.

Signed-Off By: Vivek Khandelwal <vivek@nod-labs.com>

2022-04-30 03:06 UTC, pashu123 requested changes

2022-04-30 03:06 UTC, pashu123 commented on build_tools/torchscript_e2e_heavydep_tests/functorch_inference.py
> +def inference_fn(model, input, labels):
Pass the inference function as `with torch.no grad():` Also remove `.loss.sum().backward()` since we are only intereseted in inference graph.

2022-04-30 03:06 UTC, pashu123 commented on build_tools/torchscript_e2e_heavydep_tests/functorch_inference.py
> +def inference_fn(model, input, labels):
We can have the same inference function for all these models.

2022-04-30 03:07 UTC, pashu123 commented on build_tools/torchscript_e2e_heavydep_tests/functorch_inference.py
> +def inference_fn(model, input, labels):
```
with torch.no_grad(): 
   return model(**inputs)
```

2022-05-02 13:02 UTC, silvasean requested changes

2022-05-02 13:02 UTC, silvasean commented on build_tools/torchscript_e2e_heavydep_tests/functorch_inference.py
> +model_type = AutoModelForMaskedLM
Can you make this a function instead of copying the same code every time?

2022-10-03 05:12 UTC, vivekkhandelwal1 commented
I'm closing this since this is now a stale PR.

2022-10-03 05:12 UTC, closed without merging