[WIP][TORCH] Add decomposition of `aten.linear` op
llvm/torch-mlir pull request #862
Opened 2022-05-18 16:31 UTC by Shukla-Gaurav

This commit adds decomposition of `aten.linear` op.

Signed-Off-by: Gaurav Shukla

2022-05-19 10:39 UTC, silvasean commented
Remove the TorchToLinalg code as well please since it is not not useful.

2022-06-21 19:50 UTC, Shukla-Gaurav commented
Once https://github.com/llvm/torch-mlir/pull/951 is merged, this PR will be unblocked wrt (3D, 2D) case of matmul.

2022-07-01 16:33 UTC, Shukla-Gaurav commented
@sjarus Could you please take a look into this, `ResNet18Static` is failing in torch to tosa lowering. Thanks!

2022-07-02 01:20 UTC, sjarus commented
I'll attempt to repro this early next week . Right now I'm trying to get a pipeline of pending BERT related legalizations out. Do you have detailed verbose output from the test ?

2022-07-18 15:17 UTC, Shukla-Gaurav commented
@sjarus There is a case where `aten.matmul` fails to lower to tosa. I quickly looked into it but did not get the solution. Could you please look into it?
`%3 = torch.aten.matmul %arg0, %2 : !torch.vtensor<[?,?,?],f32>, !torch.vtensor<[3,5],f32> -> !torch.vtensor<[?,?,5],f32>`.

2022-07-18 17:22 UTC, sjarus commented
What happens when you use 3, 4, 3 instead of -1, -1, -1 in the annotate args ?

2022-07-20 16:30 UTC, Shukla-Gaurav commented
@sjarus Did you get a chance to look at it?

2022-07-21 02:13 UTC, sjarus commented
Right, sorry for the delay. The experiment result appears aligned to my expectations, but I agree that if dynamic dims are unsupported then it should fail gracefully and not assert. 

It seems the best way to unblock is to keep the test static and refer in a comment to me to update the code so it doesn't assert, or better yet can pass, tho the latter is typically harder. Would that work ?

2022-08-18 16:31 UTC, Shukla-Gaurav commented
@sjarus I have made the test case partially static for now in order to pass the tosa test. Should I create a new issue for the same one?
FYI @silvasean

2022-08-18 18:56 UTC, silvasean commented
We definitely don't want to regress our testing of dynamic shapes for all backends due a limitation in the TOSA backend, so I would avoid changing the test. We can use the functionality in https://github.com/llvm/torch-mlir/pull/1242 to control the decompositions, but I need to make a PR to centralize that logic first -- will try to do that today.

@Shukla-Gaurav can you also file a bug for the TOSA assertion failure? Ideally include a `torch-mlir-opt` command line invoking the failing pass and a reduced IR snippet.

2022-08-19 00:12 UTC, silvasean commented
> We definitely don't want to regress our testing of dynamic shapes for all backends due a limitation in the TOSA backend, so I would avoid changing the test. We can use the functionality in #1242 to control the decompositions, but I need to make a PR to centralize that logic first -- will try to do that today.

See https://github.com/llvm/torch-mlir/pull/1248

2022-08-31 16:22 UTC, Shukla-Gaurav commented
@silvasean Thanks for adding support for more control over decomposition based on backend. Could you please review this again?

2022-08-31 21:46 UTC, silvasean requested changes

2022-08-31 21:46 UTC, silvasean commented on lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
> +    ArrayRef<int64_t> wShape = weightType.getSizes();
This does not work with dynamic shapes.

2022-08-31 21:48 UTC, silvasean approved these changes

2022-08-31 21:48 UTC, silvasean commented on lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
> +    ArrayRef<int64_t> wShape = weightType.getSizes();
Oh wait, yeah it does. Sorry. Usually getSizes() is not good to use for dynamic shapes but in this case it does work.

2022-08-31 21:48 UTC, silvasean commented on lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
> +    // weight must be a rank 2 matrix.
nit:
```
`weight`
```
with backticks

2022-08-31 21:53 UTC, silvasean commented on lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
> +    ArrayRef<int64_t> wShape = weightType.getSizes();
nit: I would recommend doing `llvm::to_vector(llvm::reverse(weightType.getSizes())` for this.

2022-09-07 11:28 UTC, merged