linalg: add support for clamp_min and clamp_max ops
llvm/torch-mlir pull request #896
Opened 2022-06-02 00:08 UTC by ashay

This patch adds two new operations (`AtenClampMinOp` and
`AtenClampMaxOp`) to the list of generated torch operations, along with
a corresponding translation to linalg-on-tensors.

2022-06-02 00:09 UTC, ashay commented on lib/Conversion/TorchToLinalg/Uncategorized.cpp
> +             AtenCosOp, AtenNeScalarOp, AtenNegOp, AtenMaskedFillScalarOp>(op))
This simply adds `AtenClampMaxOp` and `AtenClampMinOp` close to `AtenClampOp` to keep them all together.

2022-06-02 00:09 UTC, ashay commented on lib/Dialect/Torch/Transforms/RefineTypes.cpp
> -          AtenCumsumOp, AtenLayerNormOp, AtenClampOp, AtenNegOp, AtenFloorOp,
Same here.  This simply adds `AtenClampMaxOp` and `AtenClampMinOp` close to `AtenClampOp` to keep them all together.

2022-06-03 23:20 UTC, ramiro050 approved these changes
Thanks for this! LGTM!

2022-06-03 23:39 UTC, ramiro050 requested changes
I forgot, can you add your ops to the `illegal` list:

https://github.com/llvm/torch-mlir/blob/5705e52c631246c83e327c3e4e8b5b4d52ba6590/lib/Conversion/TorchToLinalg/Uncategorized.cpp#L1605

2022-06-04 04:27 UTC, ashay commented
Closing this in favor of PR #899.

2022-06-04 04:27 UTC, closed without merging