[MLIR][TORCH] Add decomposition of `aten.numpy_T` op
llvm/torch-mlir pull request #898
Opened 2022-06-03 12:41 UTC by vivekkhandelwal1

This commit adds the decomposition of `aten.numpy_T` op into
`aten.t` or `aten.permute` op.

Signed-Off By: Vivek Khandelwal <vivek@nod-labs.com>

2022-06-13 06:43 UTC, vivekkhandelwal1 commented
@ramiro050, please review this PR when you find the time.

2022-06-13 21:17 UTC, ramiro050 requested changes
Thanks for this! I just have one comment

2022-06-13 21:17 UTC, ramiro050 commented on lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
> +    if (inputRank > 2) {
I think the code using `AtenPermuteOp` works even for input ranks $\leq 2$. If so, then we should just use that version to simplify the decomposition.

2022-06-15 16:18 UTC, ramiro050 approved these changes
LGTM! Just one small comment

2022-06-15 16:18 UTC, ramiro050 commented on lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp
> +// Decompose `aten.numpy_T` op into `aten.permute` or `aten.t` op.
nit: comment needs to be updated

2022-06-15 18:31 UTC, merged