added def is_floating point which takes a tensor as parameter and ret…
llvm/torch-mlir pull request #901
Opened 2022-06-03 16:32 UTC by albertdmath

…urns a boolean

2022-06-07 22:24 UTC, ramiro050 commented
Make sure to run `./build_tools/update_torch_ods.sh`. I think the `has_folder=True` was added after running the script

2022-06-07 22:31 UTC, ramiro050 commented on lib/Dialect/Torch/IR/TorchOps.cpp
> +		           tensorType.getSizes().size());
The arguments to `BoolAttr::get` are `MLIRContext *, bool` (https://mlir.llvm.org/doxygen/classmlir_1_1BoolAttr.html#adb387d09645c6a87af1e6dec16791bdc). Currently, `BoolType, int` are being passed

2022-06-07 22:31 UTC, ramiro050 commented on lib/Dialect/Torch/IR/TorchOps.cpp
> +    if (typeid(tensorType).name() == "f")
You can check if a type is float by doing something like

https://github.com/llvm/torch-mlir/blob/e1b38e74dd0072f9d6d48f7c90e21912fe3e85cd/lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp#L298-L299

2022-06-07 22:31 UTC, ramiro050 commented on python/torch_mlir_e2e_test/test_suite/basic.py
> +        ([-1], torch.int32, True),
`tu.rand` generates a float tensor, so this should be `float`. If you want an int tensor, use `torch.randint`

2022-06-09 02:08 UTC, nirvedhmeshram commented on lib/Dialect/Torch/IR/TorchOps.cpp
> +  return false;
I think here you want instead of return false;
return BoolAttr::get(getContext(), false);

2022-06-09 18:43 UTC, nirvedhmeshram commented on python/torch_mlir_e2e_test/test_suite/basic.py
> +    module.forward(tu.randint(3))
I think it's torch.randint

2022-06-09 23:59 UTC, nirvedhmeshram commented on lib/Dialect/Torch/IR/TorchOps.cpp
> +	 tensorType.getDtype().isa<Float16Type>()) {
Nice! A cleaner (and complete) way is `..Dtype.isa<Float16Type, BFloat16Type, Float32Type, Float64Type>()) `

2022-06-10 18:33 UTC, nirvedhmeshram reviewed
LGTM, but lets wait for @ramiro050 's comments

2022-06-10 18:33 UTC, nirvedhmeshram approved these changes

2022-06-10 18:36 UTC, nirvedhmeshram commented on lib/Conversion/TorchToStd/TorchToStd.cpp
> +// MLIR calls "rank".
Nit: Please remove these comments

2022-06-13 22:01 UTC, ramiro050 requested changes
A few more comments

2022-06-13 22:01 UTC, ramiro050 commented on lib/Conversion/TorchToStd/TorchToStd.cpp
> +
nit: remove empty line

2022-06-13 22:11 UTC, albertdmath commented on lib/Dialect/Torch/Transforms/MaximizeValueSemantics.cpp
> +             AtenIsFloatingPointOp>(op);
So I can just remove it?

2022-06-13 22:37 UTC, ramiro050 commented on lib/Dialect/Torch/Transforms/MaximizeValueSemantics.cpp
> +             AtenIsFloatingPointOp>(op);
Yep!

2022-06-14 20:53 UTC, ramiro050 approved these changes
I just have one last comment. Other than that, everything else looks good to me

2022-06-14 20:53 UTC, ramiro050 commented on lib/Conversion/TorchToStd/TorchToStd.cpp
> +    return success();
nit: the `if` statement is not needed here. You can do

```cpp
bool result = tensorType.hasDtype() && tensorType.getDtype().isa<mlir::FloatType>();
rewriter.replaceOpWithNewOp<arith::ConstantOp>(op, BoolAttr::get(getContext(), result));
return success();
```

2022-06-15 16:54 UTC, merged