Add folding for aten.len.str and E2E test
llvm/torch-mlir pull request #969
Opened 2022-06-23 15:29 UTC by qedawkins

New contributor to torch-mlir; starting with adding support for the aten.len.str.

2022-06-27 07:37 UTC, vivekkhandelwal1 requested changes
Since you have added a folding pattern for this op, could you please add a file check test in https://github.com/llvm/torch-mlir/blob/main/test/Dialect/Torch/canonicalize.mlir as well?

2022-06-27 07:37 UTC, vivekkhandelwal1 commented on python/torch_mlir_e2e_test/test_suite/basic.py
> +class StringLength(torch.nn.Module):
Can you name this something like `LenStrModule`?

2022-06-28 05:37 UTC, vivekkhandelwal1 requested changes

2022-06-28 05:37 UTC, vivekkhandelwal1 commented on test/Dialect/Torch/canonicalize.mlir
> +// CHECK:           %[[INT3:.*]] = torch.constant.int 7
nit: `%[[INT3:.*]]` -> `%[[INT7:.*]]`

2022-06-28 05:37 UTC, vivekkhandelwal1 commented on test/Dialect/Torch/canonicalize.mlir
> +// CHECK:           %[[INT3:.*]] = torch.constant.int 0
nit: `%[[INT3:.*]]` -> `%[[INT0:.*]]`

2022-06-28 05:37 UTC, vivekkhandelwal1 commented on test/Dialect/Torch/canonicalize.mlir
> +func.func @torch.aten.len.str$non_empty() -> !torch.int {
`@torch.aten.len.str` is sufficient.

2022-06-28 15:57 UTC, vivekkhandelwal1 approved these changes
LGTM

2022-07-07 17:36 UTC, ramiro050 approved these changes
LGTM!

2022-07-07 17:41 UTC, merged